// Code generated by musgen-go. DO NOT EDIT.

package testutil

import (
	"fmt"

	com "github.com/mus-format/common-go"
	dts "github.com/mus-format/dts-go"
	arrops "github.com/mus-format/mus-go/options/array"
	bslops "github.com/mus-format/mus-go/options/byte_slice"
	mapops "github.com/mus-format/mus-go/options/map"
	slops "github.com/mus-format/mus-go/options/slice"
	strops "github.com/mus-format/mus-go/options/string"
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/raw"
	"github.com/mus-format/mus-go/unsafe"
	"github.com/mus-format/mus-go/varint"
	common_testdata "github.com/mus-format/musgen-go/testutil"
)

var (
	arrayYmhXVPWhldOIKUOzQm9zCwΞΞ     = unsafe.NewValidArraySer[[3]int, int](varint.Int, arrops.WithLenSer[int](raw.Int), arrops.WithElemValidator[int](com.ValidatorFn[int](common_testdata.ValidateZeroValue[int])))
	arrayzqFptg0WXlcvJNSDs9RquAΞΞ     = unsafe.NewValidArraySer[[3]int, int](raw.Int, arrops.WithElemValidator[int](com.ValidatorFn[int](common_testdata.ValidateZeroValue[int])))
	byteSliceShQt0Q1qciIy8uEHbapHIwΞΞ = ord.NewValidByteSliceSer(bslops.WithLenSer(varint.Int), bslops.WithLenValidator(com.ValidatorFn[int](common_testdata.ValidateLength20)))
	mapBwT0JkDMXmVKkTKBOSGoEQΞΞ       = ord.NewValidMapSer[MyInt, []MyStruct](MyIntMUS, sliceXVqHusnm8S7S1hI61k9XCAΞΞ, mapops.WithLenValidator[MyInt, []MyStruct](com.ValidatorFn[int](common_testdata.ValidateLength20)), mapops.WithKeyValidator[MyInt, []MyStruct](com.ValidatorFn[MyInt](common_testdata.ValidateZeroValue[MyInt])))
	mapJTuZruef1fMΣdu3SFmXO6AΞΞ       = ord.NewValidMapSer[float32, map[MyInt][]MyStruct](varint.Float32, mapBwT0JkDMXmVKkTKBOSGoEQΞΞ, mapops.WithLenValidator[float32, map[MyInt][]MyStruct](com.ValidatorFn[int](common_testdata.ValidateLength20)), mapops.WithKeyValidator[float32, map[MyInt][]MyStruct](com.ValidatorFn[float32](common_testdata.ValidateZeroValue[float32])))
	ptrb6lFxTAuTYvalxNJ7G6qcgΞΞ       = ord.NewPtrSer[[3]int](arrayYmhXVPWhldOIKUOzQm9zCwΞΞ)
	ptrkj4Tev4S3ri8vNeeAF9JIgΞΞ       = ord.NewPtrSer[MyStruct](MyStructMUS)
	ptruXrJOOINhUqdpΣfPWgcviAΞΞ       = ord.NewPtrSer[string](ord.String)
	sliceNR5Xw1wHcKjg6nIZXZdPΔwΞΞ     = ord.NewSliceSer[string](ord.String)
	sliceXVqHusnm8S7S1hI61k9XCAΞΞ     = ord.NewValidSliceSer[MyStruct](MyStructMUS, slops.WithLenValidator[MyStruct](com.ValidatorFn[int](common_testdata.ValidateLength20)))
	sliceirehKtIuYOl5Nn3AZ02OpAΞΞ     = ord.NewValidSliceSer[MyStruct](MyStructMUS, slops.WithLenValidator[MyStruct](com.ValidatorFn[int](common_testdata.ValidateLength20)), slops.WithElemValidator[MyStruct](com.ValidatorFn[MyStruct](common_testdata.ValidateZeroValue[MyStruct])))
	stringUXpQiATmXC1oufΣ0JTRDcgΞΞ    = ord.NewValidStringSer(strops.WithLenSer(raw.Int), strops.WithLenValidator(com.ValidatorFn[int](common_testdata.ValidateLength20)))
)

var MyIntMUS = myIntMUS{}

type myIntMUS struct{}

func (s myIntMUS) Marshal(v MyInt, bs []byte) (n int) {
	return varint.Int.Marshal(int(v), bs)
}

func (s myIntMUS) Unmarshal(bs []byte) (v MyInt, n int, err error) {
	tmp, n, err := varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v = MyInt(tmp)
	return
}

func (s myIntMUS) Size(v MyInt) (size int) {
	return varint.Int.Size(int(v))
}

func (s myIntMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

var MySliceMUS = mySliceMUS{}

type mySliceMUS struct{}

func (s mySliceMUS) Marshal(v MySlice, bs []byte) (n int) {
	return sliceNR5Xw1wHcKjg6nIZXZdPΔwΞΞ.Marshal([]string(v), bs)
}

func (s mySliceMUS) Unmarshal(bs []byte) (v MySlice, n int, err error) {
	tmp, n, err := sliceNR5Xw1wHcKjg6nIZXZdPΔwΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = MySlice(tmp)
	return
}

func (s mySliceMUS) Size(v MySlice) (size int) {
	return sliceNR5Xw1wHcKjg6nIZXZdPΔwΞΞ.Size([]string(v))
}

func (s mySliceMUS) Skip(bs []byte) (n int, err error) {
	return sliceNR5Xw1wHcKjg6nIZXZdPΔwΞΞ.Skip(bs)
}

var MyStructMUS = myStructMUS{}

type myStructMUS struct{}

func (s myStructMUS) Marshal(v MyStruct, bs []byte) (n int) {
	n = varint.Int.Marshal(v.Int, bs)
	return n + ord.String.Marshal(v.Str, bs[n:])
}

func (s myStructMUS) Unmarshal(bs []byte) (v MyStruct, n int, err error) {
	v.Int, n, err = varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	v.Str, n1, err = ord.String.Unmarshal(bs[n:])
	n += n1
	return
}

func (s myStructMUS) Size(v MyStruct) (size int) {
	size = varint.Int.Size(v.Int)
	return size + ord.String.Size(v.Str)
}

func (s myStructMUS) Skip(bs []byte) (n int, err error) {
	n, err = varint.Int.Skip(bs)
	if err != nil {
		return
	}
	var n1 int
	n1, err = ord.String.Skip(bs[n:])
	n += n1
	return
}

var MyIntDTS = dts.New[MyInt](MyIntDTM, MyIntMUS)

var MyInterfaceMUS = myInterfaceMUS{}

type myInterfaceMUS struct{}

func (s myInterfaceMUS) Marshal(v MyInterface, bs []byte) (n int) {
	switch t := v.(type) {
	case MyInt:
		return MyIntDTS.Marshal(t, bs)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s myInterfaceMUS) Unmarshal(bs []byte) (v MyInterface, n int, err error) {
	dtm, n, err := dts.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case MyIntDTM:
		v, n1, err = MyIntDTS.UnmarshalData(bs[n:])
	default:
		err = fmt.Errorf(com.ErrorPrefix+"unexpected %v DTM", dtm)
		return
	}
	n += n1
	return
}

func (s myInterfaceMUS) Size(v MyInterface) (size int) {
	switch t := v.(type) {
	case MyInt:
		return MyIntDTS.Size(t)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s myInterfaceMUS) Skip(bs []byte) (n int, err error) {
	dtm, n, err := dts.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case MyIntDTM:
		n1, err = MyIntDTS.SkipData(bs[n:])
	default:
		err = fmt.Errorf(com.ErrorPrefix+"unexpected %v DTM", dtm)
		return
	}
	n += n1
	return
}

var ComplexStructMUS = complexStructMUS{}

type complexStructMUS struct{}

func (s complexStructMUS) Marshal(v ComplexStruct, bs []byte) (n int) {
	n = ord.Bool.Marshal(v.Bool, bs)
	n += varint.Uint8.Marshal(v.Byte, bs[n:])
	n += raw.Int8.Marshal(v.Int8, bs[n:])
	n += varint.Int16.Marshal(v.Int16, bs[n:])
	n += varint.Int32.Marshal(v.Int32, bs[n:])
	n += varint.Int64.Marshal(v.Int64, bs[n:])
	n += varint.Uint8.Marshal(v.Uint8, bs[n:])
	n += varint.Uint16.Marshal(v.Uint16, bs[n:])
	n += varint.Uint32.Marshal(v.Uint32, bs[n:])
	n += varint.Uint64.Marshal(v.Uint64, bs[n:])
	n += varint.Float32.Marshal(v.Float32, bs[n:])
	n += varint.Float64.Marshal(v.Float64, bs[n:])
	n += stringUXpQiATmXC1oufΣ0JTRDcgΞΞ.Marshal(v.String, bs[n:])
	n += byteSliceShQt0Q1qciIy8uEHbapHIwΞΞ.Marshal(v.ByteSlice, bs[n:])
	n += sliceirehKtIuYOl5Nn3AZ02OpAΞΞ.Marshal(v.StructSlice, bs[n:])
	n += arrayzqFptg0WXlcvJNSDs9RquAΞΞ.Marshal(v.Array, bs[n:])
	n += ptruXrJOOINhUqdpΣfPWgcviAΞΞ.Marshal(v.PtrString, bs[n:])
	n += ptrkj4Tev4S3ri8vNeeAF9JIgΞΞ.Marshal(v.PtrStruct, bs[n:])
	n += ptruXrJOOINhUqdpΣfPWgcviAΞΞ.Marshal(v.NilPtr, bs[n:])
	n += ptrb6lFxTAuTYvalxNJ7G6qcgΞΞ.Marshal(v.PtrArray, bs[n:])
	n += mapJTuZruef1fMΣdu3SFmXO6AΞΞ.Marshal(v.Map, bs[n:])
	n += raw.TimeUnix.Marshal(v.Time, bs[n:])
	n += MySliceMUS.Marshal(v.Alias, bs[n:])
	return n + MyInterfaceMUS.Marshal(v.Interface, bs[n:])
}

func (s complexStructMUS) Unmarshal(bs []byte) (v ComplexStruct, n int, err error) {
	v.Bool, n, err = ord.Bool.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	v.Byte, n1, err = varint.Uint8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int8, n1, err = raw.Int8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int16, n1, err = varint.Int16.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int32, n1, err = varint.Int32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int64, n1, err = varint.Int64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint8, n1, err = varint.Uint8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint16, n1, err = varint.Uint16.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint32, n1, err = varint.Uint32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint64, n1, err = varint.Uint64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Float32, n1, err = varint.Float32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	err = common_testdata.ValidateZeroValue[float32](v.Float32)
	if err != nil {
		return
	}
	v.Float64, n1, err = varint.Float64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.String, n1, err = stringUXpQiATmXC1oufΣ0JTRDcgΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	err = common_testdata.ValidateZeroValue[string](v.String)
	if err != nil {
		return
	}
	v.ByteSlice, n1, err = byteSliceShQt0Q1qciIy8uEHbapHIwΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.StructSlice, n1, err = sliceirehKtIuYOl5Nn3AZ02OpAΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Array, n1, err = arrayzqFptg0WXlcvJNSDs9RquAΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.PtrString, n1, err = ptruXrJOOINhUqdpΣfPWgcviAΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.PtrStruct, n1, err = ptrkj4Tev4S3ri8vNeeAF9JIgΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.NilPtr, n1, err = ptruXrJOOINhUqdpΣfPWgcviAΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.PtrArray, n1, err = ptrb6lFxTAuTYvalxNJ7G6qcgΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Map, n1, err = mapJTuZruef1fMΣdu3SFmXO6AΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Time, n1, err = raw.TimeUnix.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Alias, n1, err = MySliceMUS.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Interface, n1, err = MyInterfaceMUS.Unmarshal(bs[n:])
	n += n1
	return
}

func (s complexStructMUS) Size(v ComplexStruct) (size int) {
	size = ord.Bool.Size(v.Bool)
	size += varint.Uint8.Size(v.Byte)
	size += raw.Int8.Size(v.Int8)
	size += varint.Int16.Size(v.Int16)
	size += varint.Int32.Size(v.Int32)
	size += varint.Int64.Size(v.Int64)
	size += varint.Uint8.Size(v.Uint8)
	size += varint.Uint16.Size(v.Uint16)
	size += varint.Uint32.Size(v.Uint32)
	size += varint.Uint64.Size(v.Uint64)
	size += varint.Float32.Size(v.Float32)
	size += varint.Float64.Size(v.Float64)
	size += stringUXpQiATmXC1oufΣ0JTRDcgΞΞ.Size(v.String)
	size += byteSliceShQt0Q1qciIy8uEHbapHIwΞΞ.Size(v.ByteSlice)
	size += sliceirehKtIuYOl5Nn3AZ02OpAΞΞ.Size(v.StructSlice)
	size += arrayzqFptg0WXlcvJNSDs9RquAΞΞ.Size(v.Array)
	size += ptruXrJOOINhUqdpΣfPWgcviAΞΞ.Size(v.PtrString)
	size += ptrkj4Tev4S3ri8vNeeAF9JIgΞΞ.Size(v.PtrStruct)
	size += ptruXrJOOINhUqdpΣfPWgcviAΞΞ.Size(v.NilPtr)
	size += ptrb6lFxTAuTYvalxNJ7G6qcgΞΞ.Size(v.PtrArray)
	size += mapJTuZruef1fMΣdu3SFmXO6AΞΞ.Size(v.Map)
	size += raw.TimeUnix.Size(v.Time)
	size += MySliceMUS.Size(v.Alias)
	return size + MyInterfaceMUS.Size(v.Interface)
}

func (s complexStructMUS) Skip(bs []byte) (n int, err error) {
	n, err = ord.Bool.Skip(bs)
	if err != nil {
		return
	}
	var n1 int
	n1, err = varint.Uint8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Int8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Int16.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Int32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Int64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint16.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Float32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Float64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = stringUXpQiATmXC1oufΣ0JTRDcgΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = byteSliceShQt0Q1qciIy8uEHbapHIwΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = sliceirehKtIuYOl5Nn3AZ02OpAΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = arrayzqFptg0WXlcvJNSDs9RquAΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ptruXrJOOINhUqdpΣfPWgcviAΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrkj4Tev4S3ri8vNeeAF9JIgΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ptruXrJOOINhUqdpΣfPWgcviAΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrb6lFxTAuTYvalxNJ7G6qcgΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = mapJTuZruef1fMΣdu3SFmXO6AΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.TimeUnix.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = MySliceMUS.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = MyInterfaceMUS.Skip(bs[n:])
	n += n1
	return
}
