// Code generated by musgen-go. DO NOT EDIT.

package testutil

import (
	"fmt"

	com "github.com/mus-format/common-go"
	dts "github.com/mus-format/dts-stream-go"
	mus "github.com/mus-format/mus-stream-go"
	"github.com/mus-format/mus-stream-go/ord"
	"github.com/mus-format/mus-stream-go/unsafe"
	struct_testdata "github.com/mus-format/musgen-go/testutil/struct"
)

var (
	arrayc2kcRUO3yqFI92Ko6AΣYΣwΞΞ = unsafe.NewArraySer[[3]int, int](unsafe.Int)
	mapToSJPYTS7HktdVDeyΣUSRwΞΞ   = ord.NewMapSer[struct_testdata.MyInt, []struct_testdata.MyStruct](MyIntMUS, sliceMgRYqΣeNwQPz2ΔMXEW83EAΞΞ)
	mapXroiUiMZXY4YbcSjepnΔ2wΞΞ   = ord.NewMapSer[float32, map[struct_testdata.MyInt][]struct_testdata.MyStruct](unsafe.Float32, mapToSJPYTS7HktdVDeyΣUSRwΞΞ)
	ptr2KTE1CartCsnLsthiΔq28AΞΞ   = ord.NewPtrSer[[3]int](arrayc2kcRUO3yqFI92Ko6AΣYΣwΞΞ)
	ptrIb43zSKQw1TUQCFzd7nBHQΞΞ   = ord.NewPtrSer[struct_testdata.MyStruct](MyStructMUS)
	ptrX7gEN6ALrRmep3ZOdW5mpgΞΞ   = ord.NewPtrSer[string](ord.String)
	sliceMgRYqΣeNwQPz2ΔMXEW83EAΞΞ = ord.NewSliceSer[struct_testdata.MyStruct](MyStructMUS)
	sliceSMYC1Nv75jigNCl4A0kDrgΞΞ = ord.NewSliceSer[string](ord.String)
)

var MyIntMUS = myIntMUS{}

type myIntMUS struct{}

func (s myIntMUS) Marshal(v struct_testdata.MyInt, w mus.Writer) (n int, err error) {
	return unsafe.Int.Marshal(int(v), w)
}

func (s myIntMUS) Unmarshal(r mus.Reader) (v struct_testdata.MyInt, n int, err error) {
	tmp, n, err := unsafe.Int.Unmarshal(r)
	if err != nil {
		return
	}
	v = struct_testdata.MyInt(tmp)
	return
}

func (s myIntMUS) Size(v struct_testdata.MyInt) (size int) {
	return unsafe.Int.Size(int(v))
}

func (s myIntMUS) Skip(r mus.Reader) (n int, err error) {
	return unsafe.Int.Skip(r)
}

var MySliceMUS = mySliceMUS{}

type mySliceMUS struct{}

func (s mySliceMUS) Marshal(v struct_testdata.MySlice, w mus.Writer) (n int, err error) {
	return sliceSMYC1Nv75jigNCl4A0kDrgΞΞ.Marshal([]string(v), w)
}

func (s mySliceMUS) Unmarshal(r mus.Reader) (v struct_testdata.MySlice, n int, err error) {
	tmp, n, err := sliceSMYC1Nv75jigNCl4A0kDrgΞΞ.Unmarshal(r)
	if err != nil {
		return
	}
	v = struct_testdata.MySlice(tmp)
	return
}

func (s mySliceMUS) Size(v struct_testdata.MySlice) (size int) {
	return sliceSMYC1Nv75jigNCl4A0kDrgΞΞ.Size([]string(v))
}

func (s mySliceMUS) Skip(r mus.Reader) (n int, err error) {
	return sliceSMYC1Nv75jigNCl4A0kDrgΞΞ.Skip(r)
}

var MyStructMUS = myStructMUS{}

type myStructMUS struct{}

func (s myStructMUS) Marshal(v struct_testdata.MyStruct, w mus.Writer) (n int, err error) {
	n, err = unsafe.Int.Marshal(v.Int, w)
	if err != nil {
		return
	}
	var n1 int
	n1, err = ord.String.Marshal(v.Str, w)
	n += n1
	return
}

func (s myStructMUS) Unmarshal(r mus.Reader) (v struct_testdata.MyStruct, n int, err error) {
	v.Int, n, err = unsafe.Int.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	v.Str, n1, err = ord.String.Unmarshal(r)
	n += n1
	return
}

func (s myStructMUS) Size(v struct_testdata.MyStruct) (size int) {
	size = unsafe.Int.Size(v.Int)
	return size + ord.String.Size(v.Str)
}

func (s myStructMUS) Skip(r mus.Reader) (n int, err error) {
	n, err = unsafe.Int.Skip(r)
	if err != nil {
		return
	}
	var n1 int
	n1, err = ord.String.Skip(r)
	n += n1
	return
}

var MyIntDTS = dts.New[struct_testdata.MyInt](MyIntDTM, MyIntMUS)

var MyInterfaceMUS = myInterfaceMUS{}

type myInterfaceMUS struct{}

func (s myInterfaceMUS) Marshal(v struct_testdata.MyInterface, w mus.Writer) (n int, err error) {
	switch t := v.(type) {
	case struct_testdata.MyInt:
		return MyIntDTS.Marshal(t, w)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s myInterfaceMUS) Unmarshal(r mus.Reader) (v struct_testdata.MyInterface, n int, err error) {
	dtm, n, err := dts.DTMSer.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case MyIntDTM:
		v, n1, err = MyIntDTS.UnmarshalData(r)
	default:
		err = fmt.Errorf(com.ErrorPrefix+"unexpected %v DTM", dtm)
		return
	}
	n += n1
	return
}

func (s myInterfaceMUS) Size(v struct_testdata.MyInterface) (size int) {
	switch t := v.(type) {
	case struct_testdata.MyInt:
		return MyIntDTS.Size(t)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s myInterfaceMUS) Skip(r mus.Reader) (n int, err error) {
	dtm, n, err := dts.DTMSer.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case MyIntDTM:
		n1, err = MyIntDTS.SkipData(r)
	default:
		err = fmt.Errorf(com.ErrorPrefix+"unexpected %v DTM", dtm)
		return
	}
	n += n1
	return
}

var ComplexStructMUS = complexStructMUS{}

type complexStructMUS struct{}

func (s complexStructMUS) Marshal(v struct_testdata.ComplexStruct, w mus.Writer) (n int, err error) {
	n, err = unsafe.Bool.Marshal(v.Bool, w)
	if err != nil {
		return
	}
	var n1 int
	n1, err = unsafe.Uint8.Marshal(v.Byte, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int8.Marshal(v.Int8, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int16.Marshal(v.Int16, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int32.Marshal(v.Int32, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int64.Marshal(v.Int64, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint8.Marshal(v.Uint8, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint16.Marshal(v.Uint16, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint32.Marshal(v.Uint32, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint64.Marshal(v.Uint64, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float32.Marshal(v.Float32, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float64.Marshal(v.Float64, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.String.Marshal(v.String, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Marshal(v.ByteSlice, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = sliceMgRYqΣeNwQPz2ΔMXEW83EAΞΞ.Marshal(v.StructSlice, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = arrayc2kcRUO3yqFI92Ko6AΣYΣwΞΞ.Marshal(v.Array, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrX7gEN6ALrRmep3ZOdW5mpgΞΞ.Marshal(v.PtrString, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrIb43zSKQw1TUQCFzd7nBHQΞΞ.Marshal(v.PtrStruct, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrX7gEN6ALrRmep3ZOdW5mpgΞΞ.Marshal(v.NilPtr, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ptr2KTE1CartCsnLsthiΔq28AΞΞ.Marshal(v.PtrArray, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = mapXroiUiMZXY4YbcSjepnΔ2wΞΞ.Marshal(v.Map, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.TimeUnix.Marshal(v.Time, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = MySliceMUS.Marshal(v.Alias, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = MyInterfaceMUS.Marshal(v.Interface, w)
	n += n1
	return
}

func (s complexStructMUS) Unmarshal(r mus.Reader) (v struct_testdata.ComplexStruct, n int, err error) {
	v.Bool, n, err = unsafe.Bool.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	v.Byte, n1, err = unsafe.Uint8.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Int8, n1, err = unsafe.Int8.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Int16, n1, err = unsafe.Int16.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Int32, n1, err = unsafe.Int32.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Int64, n1, err = unsafe.Int64.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint8, n1, err = unsafe.Uint8.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint16, n1, err = unsafe.Uint16.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint32, n1, err = unsafe.Uint32.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint64, n1, err = unsafe.Uint64.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Float32, n1, err = unsafe.Float32.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Float64, n1, err = unsafe.Float64.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.String, n1, err = ord.String.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.ByteSlice, n1, err = ord.ByteSlice.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.StructSlice, n1, err = sliceMgRYqΣeNwQPz2ΔMXEW83EAΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Array, n1, err = arrayc2kcRUO3yqFI92Ko6AΣYΣwΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.PtrString, n1, err = ptrX7gEN6ALrRmep3ZOdW5mpgΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.PtrStruct, n1, err = ptrIb43zSKQw1TUQCFzd7nBHQΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.NilPtr, n1, err = ptrX7gEN6ALrRmep3ZOdW5mpgΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.PtrArray, n1, err = ptr2KTE1CartCsnLsthiΔq28AΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Map, n1, err = mapXroiUiMZXY4YbcSjepnΔ2wΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Time, n1, err = unsafe.TimeUnix.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Alias, n1, err = MySliceMUS.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Interface, n1, err = MyInterfaceMUS.Unmarshal(r)
	n += n1
	return
}

func (s complexStructMUS) Size(v struct_testdata.ComplexStruct) (size int) {
	size = unsafe.Bool.Size(v.Bool)
	size += unsafe.Uint8.Size(v.Byte)
	size += unsafe.Int8.Size(v.Int8)
	size += unsafe.Int16.Size(v.Int16)
	size += unsafe.Int32.Size(v.Int32)
	size += unsafe.Int64.Size(v.Int64)
	size += unsafe.Uint8.Size(v.Uint8)
	size += unsafe.Uint16.Size(v.Uint16)
	size += unsafe.Uint32.Size(v.Uint32)
	size += unsafe.Uint64.Size(v.Uint64)
	size += unsafe.Float32.Size(v.Float32)
	size += unsafe.Float64.Size(v.Float64)
	size += ord.String.Size(v.String)
	size += ord.ByteSlice.Size(v.ByteSlice)
	size += sliceMgRYqΣeNwQPz2ΔMXEW83EAΞΞ.Size(v.StructSlice)
	size += arrayc2kcRUO3yqFI92Ko6AΣYΣwΞΞ.Size(v.Array)
	size += ptrX7gEN6ALrRmep3ZOdW5mpgΞΞ.Size(v.PtrString)
	size += ptrIb43zSKQw1TUQCFzd7nBHQΞΞ.Size(v.PtrStruct)
	size += ptrX7gEN6ALrRmep3ZOdW5mpgΞΞ.Size(v.NilPtr)
	size += ptr2KTE1CartCsnLsthiΔq28AΞΞ.Size(v.PtrArray)
	size += mapXroiUiMZXY4YbcSjepnΔ2wΞΞ.Size(v.Map)
	size += unsafe.TimeUnix.Size(v.Time)
	size += MySliceMUS.Size(v.Alias)
	return size + MyInterfaceMUS.Size(v.Interface)
}

func (s complexStructMUS) Skip(r mus.Reader) (n int, err error) {
	n, err = unsafe.Bool.Skip(r)
	if err != nil {
		return
	}
	var n1 int
	n1, err = unsafe.Uint8.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int8.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int16.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int32.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int64.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint8.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint16.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint32.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint64.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float32.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float64.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.String.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = sliceMgRYqΣeNwQPz2ΔMXEW83EAΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = arrayc2kcRUO3yqFI92Ko6AΣYΣwΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrX7gEN6ALrRmep3ZOdW5mpgΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrIb43zSKQw1TUQCFzd7nBHQΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrX7gEN6ALrRmep3ZOdW5mpgΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ptr2KTE1CartCsnLsthiΔq28AΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = mapXroiUiMZXY4YbcSjepnΔ2wΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.TimeUnix.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = MySliceMUS.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = MyInterfaceMUS.Skip(r)
	n += n1
	return
}
