version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "golang.org/x/mod"
        versions: ["> 0.33.0"]
      - dependency-name: "golang.org/x/tools"
        versions: ["> 0.41.0"]