// Code generated by mus-gen. DO NOT EDIT.

package stream_unsafe

import (
	"fmt"

	com "github.com/mus-format/common-go"
	"github.com/mus-format/mus-gen-go/test/types/mode"
	"github.com/mus-format/mus-stream-go"
	"github.com/mus-format/mus-stream-go/ord"
	"github.com/mus-format/mus-stream-go/typed"
	"github.com/mus-format/mus-stream-go/unsafe"
)

const (
	FullInterfaceImplDTM com.DTM = iota + 1
)

const (
	FooV1DTM com.DTM = iota + 1
	FooV2DTM
)

var (
	arraykhqoj8H1iZDaFGbnRRNCSQΞΞ = unsafe.NewArraySer[[10]int](unsafe.Int)
	mapHfQsz6AeCIBt4MICw0pP6QΞΞ   = ord.NewMapSer(unsafe.String, unsafe.Int)
	ptrTZrSs3BTZxtZSyN70GGz8gΞΞ   = ord.NewPtrSer(unsafe.Int)
	slicea9b54NTckjaAZ77kX9CsBAΞΞ = ord.NewSliceSer(unsafe.Int)
)

var FullDefinedMUS = fullDefinedMUS{}

type fullDefinedMUS struct{}

func (s fullDefinedMUS) Marshal(v mode.FullDefined, w mus.Writer) (n int, err error) {
	return unsafe.Int.Marshal(int(v), w)
}

func (s fullDefinedMUS) Unmarshal(r mus.Reader) (v mode.FullDefined, n int, err error) {
	tmp, n, err := unsafe.Int.Unmarshal(r)
	if err != nil {
		return
	}
	v = mode.FullDefined(tmp)
	return
}

func (s fullDefinedMUS) Size(v mode.FullDefined) (size int) {
	return unsafe.Int.Size(int(v))
}

func (s fullDefinedMUS) Skip(r mus.Reader) (n int, err error) {
	return unsafe.Int.Skip(r)
}

var FullInterfaceImplMUS = fullInterfaceImplMUS{}

type fullInterfaceImplMUS struct{}

func (s fullInterfaceImplMUS) Marshal(v mode.FullInterfaceImpl, w mus.Writer) (n int, err error) {
	return unsafe.String.Marshal(string(v), w)
}

func (s fullInterfaceImplMUS) Unmarshal(r mus.Reader) (v mode.FullInterfaceImpl, n int, err error) {
	tmp, n, err := unsafe.String.Unmarshal(r)
	if err != nil {
		return
	}
	v = mode.FullInterfaceImpl(tmp)
	return
}

func (s fullInterfaceImplMUS) Size(v mode.FullInterfaceImpl) (size int) {
	return unsafe.String.Size(string(v))
}

func (s fullInterfaceImplMUS) Skip(r mus.Reader) (n int, err error) {
	return unsafe.String.Skip(r)
}

var FullInterfaceImplTypedMUS = typed.NewSer(FullInterfaceImplDTM, FullInterfaceImplMUS)

var FullInterfaceMUS = fullInterfaceMUS{}

type fullInterfaceMUS struct{}

func (s fullInterfaceMUS) Marshal(v mode.FullInterface, w mus.Writer) (n int, err error) {
	switch t := v.(type) {
	case mode.FullInterfaceImpl:
		return FullInterfaceImplTypedMUS.Marshal(t, w)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s fullInterfaceMUS) Unmarshal(r mus.Reader) (v mode.FullInterface, n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case FullInterfaceImplDTM:
		v, n1, err = FullInterfaceImplTypedMUS.UnmarshalData(r)
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

func (s fullInterfaceMUS) Size(v mode.FullInterface) (size int) {
	switch t := v.(type) {
	case mode.FullInterfaceImpl:
		return FullInterfaceImplTypedMUS.Size(t)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s fullInterfaceMUS) Skip(r mus.Reader) (n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case FullInterfaceImplDTM:
		n1, err = FullInterfaceImplTypedMUS.SkipData(r)
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

var FooV1MUS = fooV1MUS{}

type fooV1MUS struct{}

func (s fooV1MUS) Marshal(v mode.FooV1, w mus.Writer) (n int, err error) {
	return unsafe.Int.Marshal(v.Num, w)
}

func (s fooV1MUS) Unmarshal(r mus.Reader) (v mode.FooV1, n int, err error) {
	v.Num, n, err = unsafe.Int.Unmarshal(r)
	return
}

func (s fooV1MUS) Size(v mode.FooV1) (size int) {
	return unsafe.Int.Size(v.Num)
}

func (s fooV1MUS) Skip(r mus.Reader) (n int, err error) {
	n, err = unsafe.Int.Skip(r)
	return
}

var FooV1TypedMUS = typed.NewSer(FooV1DTM, FooV1MUS)

var FooV2MUS = fooV2MUS{}

type fooV2MUS struct{}

func (s fooV2MUS) Marshal(v mode.FooV2, w mus.Writer) (n int, err error) {
	return unsafe.String.Marshal(string(v), w)
}

func (s fooV2MUS) Unmarshal(r mus.Reader) (v mode.FooV2, n int, err error) {
	tmp, n, err := unsafe.String.Unmarshal(r)
	if err != nil {
		return
	}
	v = mode.FooV2(tmp)
	return
}

func (s fooV2MUS) Size(v mode.FooV2) (size int) {
	return unsafe.String.Size(string(v))
}

func (s fooV2MUS) Skip(r mus.Reader) (n int, err error) {
	return unsafe.String.Skip(r)
}

var FooV2TypedMUS = typed.NewSer(FooV2DTM, FooV2MUS)

var VersionedMUS = versionedMUS{}

type versionedMUS struct{}

func (s versionedMUS) Marshal(v mode.Versioned, w mus.Writer) (n int, err error) {
	return FooV2TypedMUS.Marshal(mode.FooV2(v), w)
}

func (s versionedMUS) Unmarshal(r mus.Reader) (v mode.Versioned, n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case FooV1DTM:
		var tmp mode.FooV1
		tmp, n1, err = FooV1TypedMUS.UnmarshalData(r)
		if err != nil {
			return
		}
		v = mode.MigrateFooV1(tmp)
	case FooV2DTM:
		var tmp mode.FooV2
		tmp, n1, err = FooV2TypedMUS.UnmarshalData(r)
		if err != nil {
			return
		}
		v = mode.Versioned(tmp)
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

func (s versionedMUS) Size(v mode.Versioned) (size int) {
	return FooV2TypedMUS.Size(mode.FooV2(v))
}

func (s versionedMUS) Skip(r mus.Reader) (n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case FooV1DTM:
		n1, err = FooV1TypedMUS.SkipData(r)
	case FooV2DTM:
		n1, err = FooV2TypedMUS.SkipData(r)
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

var FullStructMUS = fullStructMUS{}

type fullStructMUS struct{}

func (s fullStructMUS) Marshal(v mode.FullStruct, w mus.Writer) (n int, err error) {
	n, err = unsafe.Int.Marshal(v.Int, w)
	if err != nil {
		return
	}
	var n1 int
	n1, err = unsafe.Int64.Marshal(v.Int64, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int32.Marshal(v.Int32, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int16.Marshal(v.Int16, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int8.Marshal(v.Int8, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint.Marshal(v.Uint, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint64.Marshal(v.Uint64, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint32.Marshal(v.Uint32, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint16.Marshal(v.Uint16, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint8.Marshal(v.Uint8, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float64.Marshal(v.Float64, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float32.Marshal(v.Float32, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint8.Marshal(v.Byte, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Bool.Marshal(v.Bool, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.String.Marshal(v.Str, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Marshal(v.ByteSlice, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Marshal(v.Uint8Slice, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.TimeUnixUTC.Marshal(v.Time, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrTZrSs3BTZxtZSyN70GGz8gΞΞ.Marshal(v.PtrInt, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = arraykhqoj8H1iZDaFGbnRRNCSQΞΞ.Marshal(v.ArrayInt, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = slicea9b54NTckjaAZ77kX9CsBAΞΞ.Marshal(v.SliceInt, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = mapHfQsz6AeCIBt4MICw0pP6QΞΞ.Marshal(v.MapStrInt, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = FullDefinedMUS.Marshal(v.Defined, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = FullInterfaceMUS.Marshal(v.Interface, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = VersionedMUS.Marshal(v.Versioned, w)
	n += n1
	return
}

func (s fullStructMUS) Unmarshal(r mus.Reader) (v mode.FullStruct, n int, err error) {
	v.Int, n, err = unsafe.Int.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	v.Int64, n1, err = unsafe.Int64.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Int32, n1, err = unsafe.Int32.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Int16, n1, err = unsafe.Int16.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Int8, n1, err = unsafe.Int8.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint, n1, err = unsafe.Uint.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint64, n1, err = unsafe.Uint64.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint32, n1, err = unsafe.Uint32.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint16, n1, err = unsafe.Uint16.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint8, n1, err = unsafe.Uint8.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Float64, n1, err = unsafe.Float64.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Float32, n1, err = unsafe.Float32.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Byte, n1, err = unsafe.Uint8.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Bool, n1, err = unsafe.Bool.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Str, n1, err = unsafe.String.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.ByteSlice, n1, err = ord.ByteSlice.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint8Slice, n1, err = ord.ByteSlice.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Time, n1, err = unsafe.TimeUnixUTC.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.PtrInt, n1, err = ptrTZrSs3BTZxtZSyN70GGz8gΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.ArrayInt, n1, err = arraykhqoj8H1iZDaFGbnRRNCSQΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.SliceInt, n1, err = slicea9b54NTckjaAZ77kX9CsBAΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.MapStrInt, n1, err = mapHfQsz6AeCIBt4MICw0pP6QΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Defined, n1, err = FullDefinedMUS.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Interface, n1, err = FullInterfaceMUS.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Versioned, n1, err = VersionedMUS.Unmarshal(r)
	n += n1
	return
}

func (s fullStructMUS) Size(v mode.FullStruct) (size int) {
	size = unsafe.Int.Size(v.Int)
	size += unsafe.Int64.Size(v.Int64)
	size += unsafe.Int32.Size(v.Int32)
	size += unsafe.Int16.Size(v.Int16)
	size += unsafe.Int8.Size(v.Int8)
	size += unsafe.Uint.Size(v.Uint)
	size += unsafe.Uint64.Size(v.Uint64)
	size += unsafe.Uint32.Size(v.Uint32)
	size += unsafe.Uint16.Size(v.Uint16)
	size += unsafe.Uint8.Size(v.Uint8)
	size += unsafe.Float64.Size(v.Float64)
	size += unsafe.Float32.Size(v.Float32)
	size += unsafe.Uint8.Size(v.Byte)
	size += unsafe.Bool.Size(v.Bool)
	size += unsafe.String.Size(v.Str)
	size += ord.ByteSlice.Size(v.ByteSlice)
	size += ord.ByteSlice.Size(v.Uint8Slice)
	size += unsafe.TimeUnixUTC.Size(v.Time)
	size += ptrTZrSs3BTZxtZSyN70GGz8gΞΞ.Size(v.PtrInt)
	size += arraykhqoj8H1iZDaFGbnRRNCSQΞΞ.Size(v.ArrayInt)
	size += slicea9b54NTckjaAZ77kX9CsBAΞΞ.Size(v.SliceInt)
	size += mapHfQsz6AeCIBt4MICw0pP6QΞΞ.Size(v.MapStrInt)
	size += FullDefinedMUS.Size(v.Defined)
	size += FullInterfaceMUS.Size(v.Interface)
	return size + VersionedMUS.Size(v.Versioned)
}

func (s fullStructMUS) Skip(r mus.Reader) (n int, err error) {
	n, err = unsafe.Int.Skip(r)
	if err != nil {
		return
	}
	var n1 int
	n1, err = unsafe.Int64.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int32.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int16.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Int8.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint64.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint32.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint16.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint8.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float64.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Float32.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Uint8.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.Bool.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.String.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = unsafe.TimeUnixUTC.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrTZrSs3BTZxtZSyN70GGz8gΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = arraykhqoj8H1iZDaFGbnRRNCSQΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = slicea9b54NTckjaAZ77kX9CsBAΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = mapHfQsz6AeCIBt4MICw0pP6QΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = FullDefinedMUS.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = FullInterfaceMUS.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = VersionedMUS.Skip(r)
	n += n1
	return
}
