// Code generated by musgen-go. DO NOT EDIT.

package testutil

import (
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/musgen-go/testutil/two_pkg/pkg"
)

var (
	sliceHVHlSXj4Z7E6BydNewjgEwΞΞ = ord.NewSliceSer[pkg.MyIntSerName](pkg.MyAwesomeIntMUS)
	sliceptgHΔ3Ryql2Z1PjDt3GIhwΞΞ = ord.NewSliceSer[pkg.MyInt](pkg.MyIntMUS)
)

var MySliceMUS = mySliceMUS{}

type mySliceMUS struct{}

func (s mySliceMUS) Marshal(v MySlice, bs []byte) (n int) {
	return sliceptgHΔ3Ryql2Z1PjDt3GIhwΞΞ.Marshal([]pkg.MyInt(v), bs)
}

func (s mySliceMUS) Unmarshal(bs []byte) (v MySlice, n int, err error) {
	tmp, n, err := sliceptgHΔ3Ryql2Z1PjDt3GIhwΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = MySlice(tmp)
	return
}

func (s mySliceMUS) Size(v MySlice) (size int) {
	return sliceptgHΔ3Ryql2Z1PjDt3GIhwΞΞ.Size([]pkg.MyInt(v))
}

func (s mySliceMUS) Skip(bs []byte) (n int, err error) {
	return sliceptgHΔ3Ryql2Z1PjDt3GIhwΞΞ.Skip(bs)
}

var MySliceSerNameMUS = mySliceSerNameMUS{}

type mySliceSerNameMUS struct{}

func (s mySliceSerNameMUS) Marshal(v MySliceSerName, bs []byte) (n int) {
	return sliceHVHlSXj4Z7E6BydNewjgEwΞΞ.Marshal([]pkg.MyIntSerName(v), bs)
}

func (s mySliceSerNameMUS) Unmarshal(bs []byte) (v MySliceSerName, n int, err error) {
	tmp, n, err := sliceHVHlSXj4Z7E6BydNewjgEwΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = MySliceSerName(tmp)
	return
}

func (s mySliceSerNameMUS) Size(v MySliceSerName) (size int) {
	return sliceHVHlSXj4Z7E6BydNewjgEwΞΞ.Size([]pkg.MyIntSerName(v))
}

func (s mySliceSerNameMUS) Skip(bs []byte) (n int, err error) {
	return sliceHVHlSXj4Z7E6BydNewjgEwΞΞ.Skip(bs)
}
