// Code generated by musgen-go. DO NOT EDIT.

package testutil

import (
	com "github.com/mus-format/common-go"
	arrops "github.com/mus-format/mus-go/options/array"
	bslops "github.com/mus-format/mus-go/options/byte_slice"
	mapops "github.com/mus-format/mus-go/options/map"
	slops "github.com/mus-format/mus-go/options/slice"
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/raw"
	"github.com/mus-format/mus-go/unsafe"
	"github.com/mus-format/mus-go/varint"
	"github.com/mus-format/musgen-go/testutil"
	generic_testdata "github.com/mus-format/musgen-go/testutil/generic"
)

var (
	array6heT764qrtTHwqnoMU1xCgΞΞ     = unsafe.NewArraySer[[3]int, int](varint.Int)
	arrayCEyPmWF0tKmBFpMlpI9SHAΞΞ     = unsafe.NewArraySer[[3]int, int](varint.Int, arrops.WithLenSer[int](raw.Int))
	arrayMY1y3enVsex8sZoReNfflAΞΞ     = unsafe.NewArraySer[[3]int, int](raw.Int)
	arrayPhuuPpbn9SsNExMVlFLLPQΞΞ     = unsafe.NewArraySer[[3]int, int](varint.Int)
	arrayTm0rTIj1bA9DDhCkRZahdwΞΞ     = unsafe.NewArraySer[[3]int, int](varint.Int, arrops.WithLenSer[int](raw.Int))
	arrayU4q83qXlbnDyΔTL7P8DVGgΞΞ     = unsafe.NewValidArraySer[[3]int, int](varint.Int, arrops.WithElemValidator[int](com.ValidatorFn[int](testutil.ValidateZeroValue[int])))
	arraybBBLnM6xZGVK2scHΔLDKvAΞΞ     = unsafe.NewValidArraySer[[3]int, int](raw.Int, arrops.WithLenSer[int](raw.Int), arrops.WithElemValidator[int](com.ValidatorFn[int](testutil.ValidateZeroValue[int])))
	byteSlicekPZuxvgUrcT5PkaZ2ΣtXdgΞΞ = ord.NewValidByteSliceSer(bslops.WithLenSer(raw.Int), bslops.WithLenValidator(com.ValidatorFn[int](testutil.ValidateLength)))
	byteSlicen2NdlFΣ2UjCJr62PZhy3EwΞΞ = ord.NewByteSliceSer(bslops.WithLenSer(raw.Int))
	byteSlices46m5GhPEΔb7iKJ9hΔtZjgΞΞ = ord.NewValidByteSliceSer(bslops.WithLenValidator(com.ValidatorFn[int](testutil.ValidateLength)))
	mapAEAvEuCZaHQTe2ΔyL7ΔoqwΞΞ       = ord.NewMapSer[int, string](varint.Int, ord.String, mapops.WithLenSer[int, string](raw.Int))
	mapDjvs23h0vEQcBHld7CwwQQΞΞ       = ord.NewValidMapSer[[3]int, map[*MyByteSlice][]generic_testdata.MySlice[generic_testdata.MyInt]](arrayTm0rTIj1bA9DDhCkRZahdwΞΞ, mapxtNpΔΔPUSeyyT695CVu70AΞΞ, mapops.WithKeyValidator[[3]int, map[*MyByteSlice][]generic_testdata.MySlice[generic_testdata.MyInt]](com.ValidatorFn[[3]int](testutil.ValidateZeroValue[[3]int])))
	mapIMIGΔΣq9dWHQbNTigIlYgQΞΞ       = ord.NewValidMapSer[int, string](varint.Int, ord.String, mapops.WithKeyValidator[int, string](com.ValidatorFn[int](testutil.ValidateZeroValue[int])))
	mapKBerZDVsT5iKQYyCzEBIzQΞΞ       = ord.NewMapSer[int, string](varint.Int, ord.String)
	mapLEnhXtAGo7FyΔHwwbJqDHwΞΞ       = ord.NewMapSer[int, string](raw.Int, ord.String)
	mapNUGWwjJJ26uwY4qRZQkΔ6AΞΞ       = ord.NewValidMapSer[int, string](varint.Int, ord.String, mapops.WithLenValidator[int, string](com.ValidatorFn[int](testutil.ValidateLength)))
	mapR3GgyzBnAvXXMbHAfZΔnXQΞΞ       = ord.NewValidMapSer[int, string](raw.Int, ord.String, mapops.WithLenSer[int, string](raw.Int), mapops.WithLenValidator[int, string](com.ValidatorFn[int](testutil.ValidateLength)), mapops.WithKeyValidator[int, string](com.ValidatorFn[int](testutil.ValidateZeroValue[int])), mapops.WithValueValidator[int, string](com.ValidatorFn[string](testutil.ValidateZeroValue[string])))
	mapYQUXw7lyUEΣNj6SmOkzmbQΞΞ       = ord.NewMapSer[int, string](varint.Int, ord.String)
	mapq78zdpdDGd1cm3OΔlRuX0AΞΞ       = ord.NewMapSer[int, string](varint.Int, ord.String)
	mapxtNpΔΔPUSeyyT695CVu70AΞΞ       = ord.NewMapSer[*MyByteSlice, []generic_testdata.MySlice[generic_testdata.MyInt]](ptrClLSjPOWj62wvxZfGE37EQΞΞ, slicexO8y1SHqFXSUvUΣA6xvoewΞΞ)
	mapyuMKfFvDP6WxQxa7xKCoΔwΞΞ       = ord.NewValidMapSer[int, string](varint.Int, ord.String, mapops.WithValueValidator[int, string](com.ValidatorFn[string](testutil.ValidateZeroValue[string])))
	ptrClLSjPOWj62wvxZfGE37EQΞΞ       = ord.NewPtrSer[MyByteSlice](MyByteSliceMUS)
	slice2pjc0CZ3poqzsDbNlFOk9wΞΞ     = ord.NewSliceSer[int](varint.Int, slops.WithLenSer[int](raw.Int))
	sliceCCZyK5M17YKUH9XmFj7zΔAΞΞ     = ord.NewSliceSer[int](varint.Int)
	sliceHSnwthfMncGflcbRQr6hIgΞΞ     = ord.NewValidSliceSer[int](raw.Int, slops.WithLenSer[int](raw.Int), slops.WithLenValidator[int](com.ValidatorFn[int](testutil.ValidateLength)), slops.WithElemValidator[int](com.ValidatorFn[int](testutil.ValidateZeroValue[int])))
	sliceKxJfC2ΔyO9DwsgCnmcLN5AΞΞ     = ord.NewSliceSer[int](varint.Int)
	sliceNlΔxflr8og2aQ1IEeOeWiQΞΞ     = ord.NewValidSliceSer[int](varint.Int, slops.WithLenValidator[int](com.ValidatorFn[int](testutil.ValidateLength)))
	sliceRTOΔvzdyK5MsTIIrqYTJmwΞΞ     = ord.NewSliceSer[int](raw.Int)
	sliceVjDNxs6FqjBYXmΔHnWLrpQΞΞ     = ord.NewValidSliceSer[int](varint.Int, slops.WithElemValidator[int](com.ValidatorFn[int](testutil.ValidateZeroValue[int])))
	slicexO8y1SHqFXSUvUΣA6xvoewΞΞ     = ord.NewSliceSer[generic_testdata.MySlice[generic_testdata.MyInt]](generic_testdata.MySliceMUS, slops.WithLenSer[generic_testdata.MySlice[generic_testdata.MyInt]](raw.Int))
)

var MyArrayMUS = myArrayMUS{}

type myArrayMUS struct{}

func (s myArrayMUS) Marshal(v MyArray, bs []byte) (n int) {
	return arrayPhuuPpbn9SsNExMVlFLLPQΞΞ.Marshal([3]int(v), bs)
}

func (s myArrayMUS) Unmarshal(bs []byte) (v MyArray, n int, err error) {
	tmp, n, err := arrayPhuuPpbn9SsNExMVlFLLPQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = MyArray(tmp)
	return
}

func (s myArrayMUS) Size(v MyArray) (size int) {
	return arrayPhuuPpbn9SsNExMVlFLLPQΞΞ.Size([3]int(v))
}

func (s myArrayMUS) Skip(bs []byte) (n int, err error) {
	return arrayPhuuPpbn9SsNExMVlFLLPQΞΞ.Skip(bs)
}

var LenEncodingMyArrayMUS = lenEncodingMyArrayMUS{}

type lenEncodingMyArrayMUS struct{}

func (s lenEncodingMyArrayMUS) Marshal(v LenEncodingMyArray, bs []byte) (n int) {
	return arrayCEyPmWF0tKmBFpMlpI9SHAΞΞ.Marshal([3]int(v), bs)
}

func (s lenEncodingMyArrayMUS) Unmarshal(bs []byte) (v LenEncodingMyArray, n int, err error) {
	tmp, n, err := arrayCEyPmWF0tKmBFpMlpI9SHAΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = LenEncodingMyArray(tmp)
	return
}

func (s lenEncodingMyArrayMUS) Size(v LenEncodingMyArray) (size int) {
	return arrayCEyPmWF0tKmBFpMlpI9SHAΞΞ.Size([3]int(v))
}

func (s lenEncodingMyArrayMUS) Skip(bs []byte) (n int, err error) {
	return arrayCEyPmWF0tKmBFpMlpI9SHAΞΞ.Skip(bs)
}

var ElemEncodingMyArrayMUS = elemEncodingMyArrayMUS{}

type elemEncodingMyArrayMUS struct{}

func (s elemEncodingMyArrayMUS) Marshal(v ElemEncodingMyArray, bs []byte) (n int) {
	return arrayMY1y3enVsex8sZoReNfflAΞΞ.Marshal([3]int(v), bs)
}

func (s elemEncodingMyArrayMUS) Unmarshal(bs []byte) (v ElemEncodingMyArray, n int, err error) {
	tmp, n, err := arrayMY1y3enVsex8sZoReNfflAΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ElemEncodingMyArray(tmp)
	return
}

func (s elemEncodingMyArrayMUS) Size(v ElemEncodingMyArray) (size int) {
	return arrayMY1y3enVsex8sZoReNfflAΞΞ.Size([3]int(v))
}

func (s elemEncodingMyArrayMUS) Skip(bs []byte) (n int, err error) {
	return arrayMY1y3enVsex8sZoReNfflAΞΞ.Skip(bs)
}

var ElemValidMyArrayMUS = elemValidMyArrayMUS{}

type elemValidMyArrayMUS struct{}

func (s elemValidMyArrayMUS) Marshal(v ElemValidMyArray, bs []byte) (n int) {
	return arrayU4q83qXlbnDyΔTL7P8DVGgΞΞ.Marshal([3]int(v), bs)
}

func (s elemValidMyArrayMUS) Unmarshal(bs []byte) (v ElemValidMyArray, n int, err error) {
	tmp, n, err := arrayU4q83qXlbnDyΔTL7P8DVGgΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ElemValidMyArray(tmp)
	return
}

func (s elemValidMyArrayMUS) Size(v ElemValidMyArray) (size int) {
	return arrayU4q83qXlbnDyΔTL7P8DVGgΞΞ.Size([3]int(v))
}

func (s elemValidMyArrayMUS) Skip(bs []byte) (n int, err error) {
	return arrayU4q83qXlbnDyΔTL7P8DVGgΞΞ.Skip(bs)
}

var ValidMyArrayMUS = validMyArrayMUS{}

type validMyArrayMUS struct{}

func (s validMyArrayMUS) Marshal(v ValidMyArray, bs []byte) (n int) {
	return array6heT764qrtTHwqnoMU1xCgΞΞ.Marshal([3]int(v), bs)
}

func (s validMyArrayMUS) Unmarshal(bs []byte) (v ValidMyArray, n int, err error) {
	tmp, n, err := array6heT764qrtTHwqnoMU1xCgΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ValidMyArray(tmp)
	err = testutil.ValidateZeroValue[ValidMyArray](v)
	return
}

func (s validMyArrayMUS) Size(v ValidMyArray) (size int) {
	return array6heT764qrtTHwqnoMU1xCgΞΞ.Size([3]int(v))
}

func (s validMyArrayMUS) Skip(bs []byte) (n int, err error) {
	return array6heT764qrtTHwqnoMU1xCgΞΞ.Skip(bs)
}

var AllMyArrayMUS = allMyArrayMUS{}

type allMyArrayMUS struct{}

func (s allMyArrayMUS) Marshal(v AllMyArray, bs []byte) (n int) {
	return arraybBBLnM6xZGVK2scHΔLDKvAΞΞ.Marshal([3]int(v), bs)
}

func (s allMyArrayMUS) Unmarshal(bs []byte) (v AllMyArray, n int, err error) {
	tmp, n, err := arraybBBLnM6xZGVK2scHΔLDKvAΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = AllMyArray(tmp)
	err = testutil.ValidateZeroValue[AllMyArray](v)
	return
}

func (s allMyArrayMUS) Size(v AllMyArray) (size int) {
	return arraybBBLnM6xZGVK2scHΔLDKvAΞΞ.Size([3]int(v))
}

func (s allMyArrayMUS) Skip(bs []byte) (n int, err error) {
	return arraybBBLnM6xZGVK2scHΔLDKvAΞΞ.Skip(bs)
}

var MyByteSliceMUS = myByteSliceMUS{}

type myByteSliceMUS struct{}

func (s myByteSliceMUS) Marshal(v MyByteSlice, bs []byte) (n int) {
	return ord.ByteSlice.Marshal([]uint8(v), bs)
}

func (s myByteSliceMUS) Unmarshal(bs []byte) (v MyByteSlice, n int, err error) {
	tmp, n, err := ord.ByteSlice.Unmarshal(bs)
	if err != nil {
		return
	}
	v = MyByteSlice(tmp)
	return
}

func (s myByteSliceMUS) Size(v MyByteSlice) (size int) {
	return ord.ByteSlice.Size([]uint8(v))
}

func (s myByteSliceMUS) Skip(bs []byte) (n int, err error) {
	return ord.ByteSlice.Skip(bs)
}

var LenEncodingMyByteSliceMUS = lenEncodingMyByteSliceMUS{}

type lenEncodingMyByteSliceMUS struct{}

func (s lenEncodingMyByteSliceMUS) Marshal(v LenEncodingMyByteSlice, bs []byte) (n int) {
	return byteSlicen2NdlFΣ2UjCJr62PZhy3EwΞΞ.Marshal([]uint8(v), bs)
}

func (s lenEncodingMyByteSliceMUS) Unmarshal(bs []byte) (v LenEncodingMyByteSlice, n int, err error) {
	tmp, n, err := byteSlicen2NdlFΣ2UjCJr62PZhy3EwΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = LenEncodingMyByteSlice(tmp)
	return
}

func (s lenEncodingMyByteSliceMUS) Size(v LenEncodingMyByteSlice) (size int) {
	return byteSlicen2NdlFΣ2UjCJr62PZhy3EwΞΞ.Size([]uint8(v))
}

func (s lenEncodingMyByteSliceMUS) Skip(bs []byte) (n int, err error) {
	return byteSlicen2NdlFΣ2UjCJr62PZhy3EwΞΞ.Skip(bs)
}

var LenValidMyByteSliceMUS = lenValidMyByteSliceMUS{}

type lenValidMyByteSliceMUS struct{}

func (s lenValidMyByteSliceMUS) Marshal(v LenValidMyByteSlice, bs []byte) (n int) {
	return byteSlices46m5GhPEΔb7iKJ9hΔtZjgΞΞ.Marshal([]uint8(v), bs)
}

func (s lenValidMyByteSliceMUS) Unmarshal(bs []byte) (v LenValidMyByteSlice, n int, err error) {
	tmp, n, err := byteSlices46m5GhPEΔb7iKJ9hΔtZjgΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = LenValidMyByteSlice(tmp)
	return
}

func (s lenValidMyByteSliceMUS) Size(v LenValidMyByteSlice) (size int) {
	return byteSlices46m5GhPEΔb7iKJ9hΔtZjgΞΞ.Size([]uint8(v))
}

func (s lenValidMyByteSliceMUS) Skip(bs []byte) (n int, err error) {
	return byteSlices46m5GhPEΔb7iKJ9hΔtZjgΞΞ.Skip(bs)
}

var ValidMyByteSliceMUS = validMyByteSliceMUS{}

type validMyByteSliceMUS struct{}

func (s validMyByteSliceMUS) Marshal(v ValidMyByteSlice, bs []byte) (n int) {
	return ord.ByteSlice.Marshal([]uint8(v), bs)
}

func (s validMyByteSliceMUS) Unmarshal(bs []byte) (v ValidMyByteSlice, n int, err error) {
	tmp, n, err := ord.ByteSlice.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ValidMyByteSlice(tmp)
	err = ValidateByteSlice1(v)
	return
}

func (s validMyByteSliceMUS) Size(v ValidMyByteSlice) (size int) {
	return ord.ByteSlice.Size([]uint8(v))
}

func (s validMyByteSliceMUS) Skip(bs []byte) (n int, err error) {
	return ord.ByteSlice.Skip(bs)
}

var AllMyByteSliceMUS = allMyByteSliceMUS{}

type allMyByteSliceMUS struct{}

func (s allMyByteSliceMUS) Marshal(v AllMyByteSlice, bs []byte) (n int) {
	return byteSlicekPZuxvgUrcT5PkaZ2ΣtXdgΞΞ.Marshal([]uint8(v), bs)
}

func (s allMyByteSliceMUS) Unmarshal(bs []byte) (v AllMyByteSlice, n int, err error) {
	tmp, n, err := byteSlicekPZuxvgUrcT5PkaZ2ΣtXdgΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = AllMyByteSlice(tmp)
	err = ValidateByteSlice2(v)
	return
}

func (s allMyByteSliceMUS) Size(v AllMyByteSlice) (size int) {
	return byteSlicekPZuxvgUrcT5PkaZ2ΣtXdgΞΞ.Size([]uint8(v))
}

func (s allMyByteSliceMUS) Skip(bs []byte) (n int, err error) {
	return byteSlicekPZuxvgUrcT5PkaZ2ΣtXdgΞΞ.Skip(bs)
}

var MySliceMUS = mySliceMUS{}

type mySliceMUS struct{}

func (s mySliceMUS) Marshal(v MySlice, bs []byte) (n int) {
	return sliceCCZyK5M17YKUH9XmFj7zΔAΞΞ.Marshal([]int(v), bs)
}

func (s mySliceMUS) Unmarshal(bs []byte) (v MySlice, n int, err error) {
	tmp, n, err := sliceCCZyK5M17YKUH9XmFj7zΔAΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = MySlice(tmp)
	return
}

func (s mySliceMUS) Size(v MySlice) (size int) {
	return sliceCCZyK5M17YKUH9XmFj7zΔAΞΞ.Size([]int(v))
}

func (s mySliceMUS) Skip(bs []byte) (n int, err error) {
	return sliceCCZyK5M17YKUH9XmFj7zΔAΞΞ.Skip(bs)
}

var LenEncodingMySliceMUS = lenEncodingMySliceMUS{}

type lenEncodingMySliceMUS struct{}

func (s lenEncodingMySliceMUS) Marshal(v LenEncodingMySlice, bs []byte) (n int) {
	return slice2pjc0CZ3poqzsDbNlFOk9wΞΞ.Marshal([]int(v), bs)
}

func (s lenEncodingMySliceMUS) Unmarshal(bs []byte) (v LenEncodingMySlice, n int, err error) {
	tmp, n, err := slice2pjc0CZ3poqzsDbNlFOk9wΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = LenEncodingMySlice(tmp)
	return
}

func (s lenEncodingMySliceMUS) Size(v LenEncodingMySlice) (size int) {
	return slice2pjc0CZ3poqzsDbNlFOk9wΞΞ.Size([]int(v))
}

func (s lenEncodingMySliceMUS) Skip(bs []byte) (n int, err error) {
	return slice2pjc0CZ3poqzsDbNlFOk9wΞΞ.Skip(bs)
}

var LenValidMySliceMUS = lenValidMySliceMUS{}

type lenValidMySliceMUS struct{}

func (s lenValidMySliceMUS) Marshal(v LenValidMySlice, bs []byte) (n int) {
	return sliceNlΔxflr8og2aQ1IEeOeWiQΞΞ.Marshal([]int(v), bs)
}

func (s lenValidMySliceMUS) Unmarshal(bs []byte) (v LenValidMySlice, n int, err error) {
	tmp, n, err := sliceNlΔxflr8og2aQ1IEeOeWiQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = LenValidMySlice(tmp)
	return
}

func (s lenValidMySliceMUS) Size(v LenValidMySlice) (size int) {
	return sliceNlΔxflr8og2aQ1IEeOeWiQΞΞ.Size([]int(v))
}

func (s lenValidMySliceMUS) Skip(bs []byte) (n int, err error) {
	return sliceNlΔxflr8og2aQ1IEeOeWiQΞΞ.Skip(bs)
}

var ElemEncodingMySliceMUS = elemEncodingMySliceMUS{}

type elemEncodingMySliceMUS struct{}

func (s elemEncodingMySliceMUS) Marshal(v ElemEncodingMySlice, bs []byte) (n int) {
	return sliceRTOΔvzdyK5MsTIIrqYTJmwΞΞ.Marshal([]int(v), bs)
}

func (s elemEncodingMySliceMUS) Unmarshal(bs []byte) (v ElemEncodingMySlice, n int, err error) {
	tmp, n, err := sliceRTOΔvzdyK5MsTIIrqYTJmwΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ElemEncodingMySlice(tmp)
	return
}

func (s elemEncodingMySliceMUS) Size(v ElemEncodingMySlice) (size int) {
	return sliceRTOΔvzdyK5MsTIIrqYTJmwΞΞ.Size([]int(v))
}

func (s elemEncodingMySliceMUS) Skip(bs []byte) (n int, err error) {
	return sliceRTOΔvzdyK5MsTIIrqYTJmwΞΞ.Skip(bs)
}

var ElemValidMySliceMUS = elemValidMySliceMUS{}

type elemValidMySliceMUS struct{}

func (s elemValidMySliceMUS) Marshal(v ElemValidMySlice, bs []byte) (n int) {
	return sliceVjDNxs6FqjBYXmΔHnWLrpQΞΞ.Marshal([]int(v), bs)
}

func (s elemValidMySliceMUS) Unmarshal(bs []byte) (v ElemValidMySlice, n int, err error) {
	tmp, n, err := sliceVjDNxs6FqjBYXmΔHnWLrpQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ElemValidMySlice(tmp)
	return
}

func (s elemValidMySliceMUS) Size(v ElemValidMySlice) (size int) {
	return sliceVjDNxs6FqjBYXmΔHnWLrpQΞΞ.Size([]int(v))
}

func (s elemValidMySliceMUS) Skip(bs []byte) (n int, err error) {
	return sliceVjDNxs6FqjBYXmΔHnWLrpQΞΞ.Skip(bs)
}

var ValidMySliceMUS = validMySliceMUS{}

type validMySliceMUS struct{}

func (s validMySliceMUS) Marshal(v ValidMySlice, bs []byte) (n int) {
	return sliceKxJfC2ΔyO9DwsgCnmcLN5AΞΞ.Marshal([]int(v), bs)
}

func (s validMySliceMUS) Unmarshal(bs []byte) (v ValidMySlice, n int, err error) {
	tmp, n, err := sliceKxJfC2ΔyO9DwsgCnmcLN5AΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ValidMySlice(tmp)
	err = ValidateMySlice1(v)
	return
}

func (s validMySliceMUS) Size(v ValidMySlice) (size int) {
	return sliceKxJfC2ΔyO9DwsgCnmcLN5AΞΞ.Size([]int(v))
}

func (s validMySliceMUS) Skip(bs []byte) (n int, err error) {
	return sliceKxJfC2ΔyO9DwsgCnmcLN5AΞΞ.Skip(bs)
}

var AllMySliceMUS = allMySliceMUS{}

type allMySliceMUS struct{}

func (s allMySliceMUS) Marshal(v AllMySlice, bs []byte) (n int) {
	return sliceHSnwthfMncGflcbRQr6hIgΞΞ.Marshal([]int(v), bs)
}

func (s allMySliceMUS) Unmarshal(bs []byte) (v AllMySlice, n int, err error) {
	tmp, n, err := sliceHSnwthfMncGflcbRQr6hIgΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = AllMySlice(tmp)
	err = ValidateMySlice2(v)
	return
}

func (s allMySliceMUS) Size(v AllMySlice) (size int) {
	return sliceHSnwthfMncGflcbRQr6hIgΞΞ.Size([]int(v))
}

func (s allMySliceMUS) Skip(bs []byte) (n int, err error) {
	return sliceHSnwthfMncGflcbRQr6hIgΞΞ.Skip(bs)
}

var MyMapMUS = myMapMUS{}

type myMapMUS struct{}

func (s myMapMUS) Marshal(v MyMap, bs []byte) (n int) {
	return mapq78zdpdDGd1cm3OΔlRuX0AΞΞ.Marshal(map[int]string(v), bs)
}

func (s myMapMUS) Unmarshal(bs []byte) (v MyMap, n int, err error) {
	tmp, n, err := mapq78zdpdDGd1cm3OΔlRuX0AΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = MyMap(tmp)
	return
}

func (s myMapMUS) Size(v MyMap) (size int) {
	return mapq78zdpdDGd1cm3OΔlRuX0AΞΞ.Size(map[int]string(v))
}

func (s myMapMUS) Skip(bs []byte) (n int, err error) {
	return mapq78zdpdDGd1cm3OΔlRuX0AΞΞ.Skip(bs)
}

var LenEncodingMyMapMUS = lenEncodingMyMapMUS{}

type lenEncodingMyMapMUS struct{}

func (s lenEncodingMyMapMUS) Marshal(v LenEncodingMyMap, bs []byte) (n int) {
	return mapAEAvEuCZaHQTe2ΔyL7ΔoqwΞΞ.Marshal(map[int]string(v), bs)
}

func (s lenEncodingMyMapMUS) Unmarshal(bs []byte) (v LenEncodingMyMap, n int, err error) {
	tmp, n, err := mapAEAvEuCZaHQTe2ΔyL7ΔoqwΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = LenEncodingMyMap(tmp)
	return
}

func (s lenEncodingMyMapMUS) Size(v LenEncodingMyMap) (size int) {
	return mapAEAvEuCZaHQTe2ΔyL7ΔoqwΞΞ.Size(map[int]string(v))
}

func (s lenEncodingMyMapMUS) Skip(bs []byte) (n int, err error) {
	return mapAEAvEuCZaHQTe2ΔyL7ΔoqwΞΞ.Skip(bs)
}

var LenValidMyMapMUS = lenValidMyMapMUS{}

type lenValidMyMapMUS struct{}

func (s lenValidMyMapMUS) Marshal(v LenValidMyMap, bs []byte) (n int) {
	return mapNUGWwjJJ26uwY4qRZQkΔ6AΞΞ.Marshal(map[int]string(v), bs)
}

func (s lenValidMyMapMUS) Unmarshal(bs []byte) (v LenValidMyMap, n int, err error) {
	tmp, n, err := mapNUGWwjJJ26uwY4qRZQkΔ6AΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = LenValidMyMap(tmp)
	return
}

func (s lenValidMyMapMUS) Size(v LenValidMyMap) (size int) {
	return mapNUGWwjJJ26uwY4qRZQkΔ6AΞΞ.Size(map[int]string(v))
}

func (s lenValidMyMapMUS) Skip(bs []byte) (n int, err error) {
	return mapNUGWwjJJ26uwY4qRZQkΔ6AΞΞ.Skip(bs)
}

var KeyEncodingMyMapMUS = keyEncodingMyMapMUS{}

type keyEncodingMyMapMUS struct{}

func (s keyEncodingMyMapMUS) Marshal(v KeyEncodingMyMap, bs []byte) (n int) {
	return mapLEnhXtAGo7FyΔHwwbJqDHwΞΞ.Marshal(map[int]string(v), bs)
}

func (s keyEncodingMyMapMUS) Unmarshal(bs []byte) (v KeyEncodingMyMap, n int, err error) {
	tmp, n, err := mapLEnhXtAGo7FyΔHwwbJqDHwΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = KeyEncodingMyMap(tmp)
	return
}

func (s keyEncodingMyMapMUS) Size(v KeyEncodingMyMap) (size int) {
	return mapLEnhXtAGo7FyΔHwwbJqDHwΞΞ.Size(map[int]string(v))
}

func (s keyEncodingMyMapMUS) Skip(bs []byte) (n int, err error) {
	return mapLEnhXtAGo7FyΔHwwbJqDHwΞΞ.Skip(bs)
}

var KeyValidMyMapMUS = keyValidMyMapMUS{}

type keyValidMyMapMUS struct{}

func (s keyValidMyMapMUS) Marshal(v KeyValidMyMap, bs []byte) (n int) {
	return mapIMIGΔΣq9dWHQbNTigIlYgQΞΞ.Marshal(map[int]string(v), bs)
}

func (s keyValidMyMapMUS) Unmarshal(bs []byte) (v KeyValidMyMap, n int, err error) {
	tmp, n, err := mapIMIGΔΣq9dWHQbNTigIlYgQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = KeyValidMyMap(tmp)
	return
}

func (s keyValidMyMapMUS) Size(v KeyValidMyMap) (size int) {
	return mapIMIGΔΣq9dWHQbNTigIlYgQΞΞ.Size(map[int]string(v))
}

func (s keyValidMyMapMUS) Skip(bs []byte) (n int, err error) {
	return mapIMIGΔΣq9dWHQbNTigIlYgQΞΞ.Skip(bs)
}

var ElemEncodingMyMapMUS = elemEncodingMyMapMUS{}

type elemEncodingMyMapMUS struct{}

func (s elemEncodingMyMapMUS) Marshal(v ElemEncodingMyMap, bs []byte) (n int) {
	return mapKBerZDVsT5iKQYyCzEBIzQΞΞ.Marshal(map[int]string(v), bs)
}

func (s elemEncodingMyMapMUS) Unmarshal(bs []byte) (v ElemEncodingMyMap, n int, err error) {
	tmp, n, err := mapKBerZDVsT5iKQYyCzEBIzQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ElemEncodingMyMap(tmp)
	return
}

func (s elemEncodingMyMapMUS) Size(v ElemEncodingMyMap) (size int) {
	return mapKBerZDVsT5iKQYyCzEBIzQΞΞ.Size(map[int]string(v))
}

func (s elemEncodingMyMapMUS) Skip(bs []byte) (n int, err error) {
	return mapKBerZDVsT5iKQYyCzEBIzQΞΞ.Skip(bs)
}

var ElemValidMyMapMUS = elemValidMyMapMUS{}

type elemValidMyMapMUS struct{}

func (s elemValidMyMapMUS) Marshal(v ElemValidMyMap, bs []byte) (n int) {
	return mapyuMKfFvDP6WxQxa7xKCoΔwΞΞ.Marshal(map[int]string(v), bs)
}

func (s elemValidMyMapMUS) Unmarshal(bs []byte) (v ElemValidMyMap, n int, err error) {
	tmp, n, err := mapyuMKfFvDP6WxQxa7xKCoΔwΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ElemValidMyMap(tmp)
	return
}

func (s elemValidMyMapMUS) Size(v ElemValidMyMap) (size int) {
	return mapyuMKfFvDP6WxQxa7xKCoΔwΞΞ.Size(map[int]string(v))
}

func (s elemValidMyMapMUS) Skip(bs []byte) (n int, err error) {
	return mapyuMKfFvDP6WxQxa7xKCoΔwΞΞ.Skip(bs)
}

var ValidMyMapMUS = validMyMapMUS{}

type validMyMapMUS struct{}

func (s validMyMapMUS) Marshal(v ValidMyMap, bs []byte) (n int) {
	return mapYQUXw7lyUEΣNj6SmOkzmbQΞΞ.Marshal(map[int]string(v), bs)
}

func (s validMyMapMUS) Unmarshal(bs []byte) (v ValidMyMap, n int, err error) {
	tmp, n, err := mapYQUXw7lyUEΣNj6SmOkzmbQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ValidMyMap(tmp)
	err = ValidateMyMap1(v)
	return
}

func (s validMyMapMUS) Size(v ValidMyMap) (size int) {
	return mapYQUXw7lyUEΣNj6SmOkzmbQΞΞ.Size(map[int]string(v))
}

func (s validMyMapMUS) Skip(bs []byte) (n int, err error) {
	return mapYQUXw7lyUEΣNj6SmOkzmbQΞΞ.Skip(bs)
}

var AllMyMapMUS = allMyMapMUS{}

type allMyMapMUS struct{}

func (s allMyMapMUS) Marshal(v AllMyMap, bs []byte) (n int) {
	return mapR3GgyzBnAvXXMbHAfZΔnXQΞΞ.Marshal(map[int]string(v), bs)
}

func (s allMyMapMUS) Unmarshal(bs []byte) (v AllMyMap, n int, err error) {
	tmp, n, err := mapR3GgyzBnAvXXMbHAfZΔnXQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = AllMyMap(tmp)
	err = ValidateMyMap2(v)
	return
}

func (s allMyMapMUS) Size(v AllMyMap) (size int) {
	return mapR3GgyzBnAvXXMbHAfZΔnXQΞΞ.Size(map[int]string(v))
}

func (s allMyMapMUS) Skip(bs []byte) (n int, err error) {
	return mapR3GgyzBnAvXXMbHAfZΔnXQΞΞ.Skip(bs)
}

var ComplexMapMUS = complexMapMUS{}

type complexMapMUS struct{}

func (s complexMapMUS) Marshal(v ComplexMap, bs []byte) (n int) {
	return mapDjvs23h0vEQcBHld7CwwQQΞΞ.Marshal(map[[3]int]map[*MyByteSlice][]generic_testdata.MySlice[generic_testdata.MyInt](v), bs)
}

func (s complexMapMUS) Unmarshal(bs []byte) (v ComplexMap, n int, err error) {
	tmp, n, err := mapDjvs23h0vEQcBHld7CwwQQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ComplexMap(tmp)
	return
}

func (s complexMapMUS) Size(v ComplexMap) (size int) {
	return mapDjvs23h0vEQcBHld7CwwQQΞΞ.Size(map[[3]int]map[*MyByteSlice][]generic_testdata.MySlice[generic_testdata.MyInt](v))
}

func (s complexMapMUS) Skip(bs []byte) (n int, err error) {
	return mapDjvs23h0vEQcBHld7CwwQQΞΞ.Skip(bs)
}
