// Code generated by mus-gen. DO NOT EDIT.

package sub

import (
	"github.com/mus-format/mus-go/ord"
)

var BarMUS = barMUS{}

type barMUS struct{}

func (s barMUS) Marshal(v Bar, bs []byte) (n int) {
	return ord.String.Marshal(string(v), bs)
}

func (s barMUS) Unmarshal(bs []byte) (v Bar, n int, err error) {
	tmp, n, err := ord.String.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Bar(tmp)
	return
}

func (s barMUS) Size(v Bar) (size int) {
	return ord.String.Size(string(v))
}

func (s barMUS) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}
