// Code generated by mus-gen. DO NOT EDIT.

package custom_sername

import (
	"github.com/mus-format/mus-gen-go/test/genopts/custom_sername/pkg"
)

var CustomSerNameMUS = customSerNameMUS{}

type customSerNameMUS struct{}

func (s customSerNameMUS) Marshal(v Foo, bs []byte) (n int) {
	return pkg.PointMUS.Marshal(v.Point, bs)
}

func (s customSerNameMUS) Unmarshal(bs []byte) (v Foo, n int, err error) {
	v.Point, n, err = pkg.PointMUS.Unmarshal(bs)
	return
}

func (s customSerNameMUS) Size(v Foo) (size int) {
	return pkg.PointMUS.Size(v.Point)
}

func (s customSerNameMUS) Skip(bs []byte) (n int, err error) {
	n, err = pkg.PointMUS.Skip(bs)
	return
}
