// Code generated by mus-gen-go. DO NOT EDIT.

package stream_safe

import (
	"fmt"

	com "github.com/mus-format/common-go"
	"github.com/mus-format/mus-gen-go/test/types/mode"
	"github.com/mus-format/mus-stream-go"
	"github.com/mus-format/mus-stream-go/ord"
	"github.com/mus-format/mus-stream-go/raw"
	"github.com/mus-format/mus-stream-go/typed"
	"github.com/mus-format/mus-stream-go/unsafe"
	"github.com/mus-format/mus-stream-go/varint"
)

const (
	FullInterfaceImplDTM com.DTM = iota + 1
)

var (
	arraykhqoj8H1iZDaFGbnRRNCSQΞΞ = unsafe.NewArraySer[[10]int](varint.Int)
	mapHfQsz6AeCIBt4MICw0pP6QΞΞ   = ord.NewMapSer(ord.String, varint.Int)
	ptrTZrSs3BTZxtZSyN70GGz8gΞΞ   = ord.NewPtrSer(varint.Int)
	slicea9b54NTckjaAZ77kX9CsBAΞΞ = ord.NewSliceSer(varint.Int)
)

var FullDefinedMUS = fullDefinedMUS{}

type fullDefinedMUS struct{}

func (s fullDefinedMUS) Marshal(v mode.FullDefined, w mus.Writer) (n int, err error) {
	return varint.Int.Marshal(int(v), w)
}

func (s fullDefinedMUS) Unmarshal(r mus.Reader) (v mode.FullDefined, n int, err error) {
	tmp, n, err := varint.Int.Unmarshal(r)
	if err != nil {
		return
	}
	v = mode.FullDefined(tmp)
	return
}

func (s fullDefinedMUS) Size(v mode.FullDefined) (size int) {
	return varint.Int.Size(int(v))
}

func (s fullDefinedMUS) Skip(r mus.Reader) (n int, err error) {
	return varint.Int.Skip(r)
}

var FullInterfaceImplMUS = fullInterfaceImplMUS{}

type fullInterfaceImplMUS struct{}

func (s fullInterfaceImplMUS) Marshal(v mode.FullInterfaceImpl, w mus.Writer) (n int, err error) {
	return ord.String.Marshal(string(v), w)
}

func (s fullInterfaceImplMUS) Unmarshal(r mus.Reader) (v mode.FullInterfaceImpl, n int, err error) {
	tmp, n, err := ord.String.Unmarshal(r)
	if err != nil {
		return
	}
	v = mode.FullInterfaceImpl(tmp)
	return
}

func (s fullInterfaceImplMUS) Size(v mode.FullInterfaceImpl) (size int) {
	return ord.String.Size(string(v))
}

func (s fullInterfaceImplMUS) Skip(r mus.Reader) (n int, err error) {
	return ord.String.Skip(r)
}

var FullInterfaceImplTypedMUS = typed.NewTypedSer(FullInterfaceImplDTM, FullInterfaceImplMUS)

var FullInterfaceMUS = fullInterfaceMUS{}

type fullInterfaceMUS struct{}

func (s fullInterfaceMUS) Marshal(v mode.FullInterface, w mus.Writer) (n int, err error) {
	switch t := v.(type) {
	case mode.FullInterfaceImpl:
		return FullInterfaceImplTypedMUS.Marshal(t, w)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s fullInterfaceMUS) Unmarshal(r mus.Reader) (v mode.FullInterface, n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case FullInterfaceImplDTM:
		v, n1, err = FullInterfaceImplTypedMUS.UnmarshalData(r)
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

func (s fullInterfaceMUS) Size(v mode.FullInterface) (size int) {
	switch t := v.(type) {
	case mode.FullInterfaceImpl:
		return FullInterfaceImplTypedMUS.Size(t)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s fullInterfaceMUS) Skip(r mus.Reader) (n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case FullInterfaceImplDTM:
		n1, err = FullInterfaceImplTypedMUS.SkipData(r)
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

var FullStructMUS = fullStructMUS{}

type fullStructMUS struct{}

func (s fullStructMUS) Marshal(v mode.FullStruct, w mus.Writer) (n int, err error) {
	n, err = varint.Int.Marshal(v.Int, w)
	if err != nil {
		return
	}
	var n1 int
	n1, err = varint.Int64.Marshal(v.Int64, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Int32.Marshal(v.Int32, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Int16.Marshal(v.Int16, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Int8.Marshal(v.Int8, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint.Marshal(v.Uint, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint64.Marshal(v.Uint64, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint32.Marshal(v.Uint32, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint16.Marshal(v.Uint16, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Uint8.Marshal(v.Uint8, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Float64.Marshal(v.Float64, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Float32.Marshal(v.Float32, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Uint8.Marshal(v.Byte, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.Bool.Marshal(v.Bool, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.String.Marshal(v.Str, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Marshal(v.ByteSlice, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Marshal(v.Uint8Slice, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.TimeUnixUTC.Marshal(v.Time, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrTZrSs3BTZxtZSyN70GGz8gΞΞ.Marshal(v.PtrInt, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = arraykhqoj8H1iZDaFGbnRRNCSQΞΞ.Marshal(v.ArrayInt, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = slicea9b54NTckjaAZ77kX9CsBAΞΞ.Marshal(v.SliceInt, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = mapHfQsz6AeCIBt4MICw0pP6QΞΞ.Marshal(v.MapStrInt, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = FullDefinedMUS.Marshal(v.Defined, w)
	n += n1
	if err != nil {
		return
	}
	n1, err = FullInterfaceMUS.Marshal(v.Interface, w)
	n += n1
	return
}

func (s fullStructMUS) Unmarshal(r mus.Reader) (v mode.FullStruct, n int, err error) {
	v.Int, n, err = varint.Int.Unmarshal(r)
	if err != nil {
		return
	}
	var n1 int
	v.Int64, n1, err = varint.Int64.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Int32, n1, err = varint.Int32.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Int16, n1, err = varint.Int16.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Int8, n1, err = raw.Int8.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint, n1, err = varint.Uint.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint64, n1, err = varint.Uint64.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint32, n1, err = varint.Uint32.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint16, n1, err = varint.Uint16.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint8, n1, err = raw.Uint8.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Float64, n1, err = raw.Float64.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Float32, n1, err = raw.Float32.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Byte, n1, err = raw.Uint8.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Bool, n1, err = ord.Bool.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Str, n1, err = ord.String.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.ByteSlice, n1, err = ord.ByteSlice.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Uint8Slice, n1, err = ord.ByteSlice.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Time, n1, err = raw.TimeUnixUTC.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.PtrInt, n1, err = ptrTZrSs3BTZxtZSyN70GGz8gΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.ArrayInt, n1, err = arraykhqoj8H1iZDaFGbnRRNCSQΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.SliceInt, n1, err = slicea9b54NTckjaAZ77kX9CsBAΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.MapStrInt, n1, err = mapHfQsz6AeCIBt4MICw0pP6QΞΞ.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Defined, n1, err = FullDefinedMUS.Unmarshal(r)
	n += n1
	if err != nil {
		return
	}
	v.Interface, n1, err = FullInterfaceMUS.Unmarshal(r)
	n += n1
	return
}

func (s fullStructMUS) Size(v mode.FullStruct) (size int) {
	size = varint.Int.Size(v.Int)
	size += varint.Int64.Size(v.Int64)
	size += varint.Int32.Size(v.Int32)
	size += varint.Int16.Size(v.Int16)
	size += raw.Int8.Size(v.Int8)
	size += varint.Uint.Size(v.Uint)
	size += varint.Uint64.Size(v.Uint64)
	size += varint.Uint32.Size(v.Uint32)
	size += varint.Uint16.Size(v.Uint16)
	size += raw.Uint8.Size(v.Uint8)
	size += raw.Float64.Size(v.Float64)
	size += raw.Float32.Size(v.Float32)
	size += raw.Uint8.Size(v.Byte)
	size += ord.Bool.Size(v.Bool)
	size += ord.String.Size(v.Str)
	size += ord.ByteSlice.Size(v.ByteSlice)
	size += ord.ByteSlice.Size(v.Uint8Slice)
	size += raw.TimeUnixUTC.Size(v.Time)
	size += ptrTZrSs3BTZxtZSyN70GGz8gΞΞ.Size(v.PtrInt)
	size += arraykhqoj8H1iZDaFGbnRRNCSQΞΞ.Size(v.ArrayInt)
	size += slicea9b54NTckjaAZ77kX9CsBAΞΞ.Size(v.SliceInt)
	size += mapHfQsz6AeCIBt4MICw0pP6QΞΞ.Size(v.MapStrInt)
	size += FullDefinedMUS.Size(v.Defined)
	return size + FullInterfaceMUS.Size(v.Interface)
}

func (s fullStructMUS) Skip(r mus.Reader) (n int, err error) {
	n, err = varint.Int.Skip(r)
	if err != nil {
		return
	}
	var n1 int
	n1, err = varint.Int64.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Int32.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Int16.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Int8.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint64.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint32.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint16.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Uint8.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Float64.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Float32.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Uint8.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.Bool.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.String.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.TimeUnixUTC.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrTZrSs3BTZxtZSyN70GGz8gΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = arraykhqoj8H1iZDaFGbnRRNCSQΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = slicea9b54NTckjaAZ77kX9CsBAΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = mapHfQsz6AeCIBt4MICw0pP6QΞΞ.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = FullDefinedMUS.Skip(r)
	n += n1
	if err != nil {
		return
	}
	n1, err = FullInterfaceMUS.Skip(r)
	n += n1
	return
}
