// Code generated by mus-gen. DO NOT EDIT.

package import_alias

import (
	pkg1_sub "github.com/mus-format/mus-gen-go/test/genopts/import_alias/pkg1/sub"
	pkg2_sub "github.com/mus-format/mus-gen-go/test/genopts/import_alias/pkg2/sub"
)

var ZooMUS = zooMUS{}

type zooMUS struct{}

func (s zooMUS) Marshal(v Zoo, bs []byte) (n int) {
	n = pkg1_sub.FooMUS.Marshal(v.Foo, bs)
	return n + pkg2_sub.BarMUS.Marshal(v.Bar, bs[n:])
}

func (s zooMUS) Unmarshal(bs []byte) (v Zoo, n int, err error) {
	v.Foo, n, err = pkg1_sub.FooMUS.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	v.Bar, n1, err = pkg2_sub.BarMUS.Unmarshal(bs[n:])
	n += n1
	return
}

func (s zooMUS) Size(v Zoo) (size int) {
	size = pkg1_sub.FooMUS.Size(v.Foo)
	return size + pkg2_sub.BarMUS.Size(v.Bar)
}

func (s zooMUS) Skip(bs []byte) (n int, err error) {
	n, err = pkg1_sub.FooMUS.Skip(bs)
	if err != nil {
		return
	}
	var n1 int
	n1, err = pkg2_sub.BarMUS.Skip(bs[n:])
	n += n1
	return
}
