// Code generated by mus-gen. DO NOT EDIT.

package safe

import (
	"fmt"

	com "github.com/mus-format/common-go"
	"github.com/mus-format/mus-gen-go/test/types/mode"
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/raw"
	"github.com/mus-format/mus-go/typed"
	"github.com/mus-format/mus-go/unsafe"
	"github.com/mus-format/mus-go/varint"
)

const (
	FullInterfaceImplDTM com.DTM = iota + 1
)

const (
	FooV1DTM com.DTM = iota + 1
	FooV2DTM
)

var (
	arraykhqoj8H1iZDaFGbnRRNCSQΞΞ = unsafe.NewArraySer[[10]int](varint.Int)
	mapHfQsz6AeCIBt4MICw0pP6QΞΞ   = ord.NewMapSer(ord.String, varint.Int)
	ptrTZrSs3BTZxtZSyN70GGz8gΞΞ   = ord.NewPtrSer(varint.Int)
	slicea9b54NTckjaAZ77kX9CsBAΞΞ = ord.NewSliceSer(varint.Int)
)

var FullDefinedMUS = fullDefinedMUS{}

type fullDefinedMUS struct{}

func (s fullDefinedMUS) Marshal(v mode.FullDefined, bs []byte) (n int) {
	return varint.Int.Marshal(int(v), bs)
}

func (s fullDefinedMUS) Unmarshal(bs []byte) (v mode.FullDefined, n int, err error) {
	tmp, n, err := varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v = mode.FullDefined(tmp)
	return
}

func (s fullDefinedMUS) Size(v mode.FullDefined) (size int) {
	return varint.Int.Size(int(v))
}

func (s fullDefinedMUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

var FullInterfaceImplMUS = fullInterfaceImplMUS{}

type fullInterfaceImplMUS struct{}

func (s fullInterfaceImplMUS) Marshal(v mode.FullInterfaceImpl, bs []byte) (n int) {
	return ord.String.Marshal(string(v), bs)
}

func (s fullInterfaceImplMUS) Unmarshal(bs []byte) (v mode.FullInterfaceImpl, n int, err error) {
	tmp, n, err := ord.String.Unmarshal(bs)
	if err != nil {
		return
	}
	v = mode.FullInterfaceImpl(tmp)
	return
}

func (s fullInterfaceImplMUS) Size(v mode.FullInterfaceImpl) (size int) {
	return ord.String.Size(string(v))
}

func (s fullInterfaceImplMUS) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}

var FullInterfaceImplTypedMUS = typed.NewSer(FullInterfaceImplDTM, FullInterfaceImplMUS)

var FullInterfaceMUS = fullInterfaceMUS{}

type fullInterfaceMUS struct{}

func (s fullInterfaceMUS) Marshal(v mode.FullInterface, bs []byte) (n int) {
	switch t := v.(type) {
	case mode.FullInterfaceImpl:
		return FullInterfaceImplTypedMUS.Marshal(t, bs)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s fullInterfaceMUS) Unmarshal(bs []byte) (v mode.FullInterface, n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case FullInterfaceImplDTM:
		v, n1, err = FullInterfaceImplTypedMUS.UnmarshalData(bs[n:])
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

func (s fullInterfaceMUS) Size(v mode.FullInterface) (size int) {
	switch t := v.(type) {
	case mode.FullInterfaceImpl:
		return FullInterfaceImplTypedMUS.Size(t)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s fullInterfaceMUS) Skip(bs []byte) (n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case FullInterfaceImplDTM:
		n1, err = FullInterfaceImplTypedMUS.SkipData(bs[n:])
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

var FooV1MUS = fooV1MUS{}

type fooV1MUS struct{}

func (s fooV1MUS) Marshal(v mode.FooV1, bs []byte) (n int) {
	return varint.Int.Marshal(v.Num, bs)
}

func (s fooV1MUS) Unmarshal(bs []byte) (v mode.FooV1, n int, err error) {
	v.Num, n, err = varint.Int.Unmarshal(bs)
	return
}

func (s fooV1MUS) Size(v mode.FooV1) (size int) {
	return varint.Int.Size(v.Num)
}

func (s fooV1MUS) Skip(bs []byte) (n int, err error) {
	n, err = varint.Int.Skip(bs)
	return
}

var FooV1TypedMUS = typed.NewSer(FooV1DTM, FooV1MUS)

var FooV2MUS = fooV2MUS{}

type fooV2MUS struct{}

func (s fooV2MUS) Marshal(v mode.FooV2, bs []byte) (n int) {
	return ord.String.Marshal(string(v), bs)
}

func (s fooV2MUS) Unmarshal(bs []byte) (v mode.FooV2, n int, err error) {
	tmp, n, err := ord.String.Unmarshal(bs)
	if err != nil {
		return
	}
	v = mode.FooV2(tmp)
	return
}

func (s fooV2MUS) Size(v mode.FooV2) (size int) {
	return ord.String.Size(string(v))
}

func (s fooV2MUS) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}

var FooV2TypedMUS = typed.NewSer(FooV2DTM, FooV2MUS)

var VersionedMUS = versionedMUS{}

type versionedMUS struct{}

func (s versionedMUS) Marshal(v mode.Versioned, bs []byte) (n int) {
	return FooV2TypedMUS.Marshal(mode.FooV2(v), bs)
}

func (s versionedMUS) Unmarshal(bs []byte) (v mode.Versioned, n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case FooV1DTM:
		var tmp mode.FooV1
		tmp, n1, err = FooV1TypedMUS.UnmarshalData(bs[n:])
		if err != nil {
			return
		}
		v = mode.MigrateFooV1(tmp)
	case FooV2DTM:
		var tmp mode.FooV2
		tmp, n1, err = FooV2TypedMUS.UnmarshalData(bs[n:])
		if err != nil {
			return
		}
		v = mode.Versioned(tmp)
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

func (s versionedMUS) Size(v mode.Versioned) (size int) {
	return FooV2TypedMUS.Size(mode.FooV2(v))
}

func (s versionedMUS) Skip(bs []byte) (n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case FooV1DTM:
		n1, err = FooV1TypedMUS.SkipData(bs[n:])
	case FooV2DTM:
		n1, err = FooV2TypedMUS.SkipData(bs[n:])
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

var FullStructMUS = fullStructMUS{}

type fullStructMUS struct{}

func (s fullStructMUS) Marshal(v mode.FullStruct, bs []byte) (n int) {
	n = varint.Int.Marshal(v.Int, bs)
	n += varint.Int64.Marshal(v.Int64, bs[n:])
	n += varint.Int32.Marshal(v.Int32, bs[n:])
	n += varint.Int16.Marshal(v.Int16, bs[n:])
	n += raw.Int8.Marshal(v.Int8, bs[n:])
	n += varint.Uint.Marshal(v.Uint, bs[n:])
	n += varint.Uint64.Marshal(v.Uint64, bs[n:])
	n += varint.Uint32.Marshal(v.Uint32, bs[n:])
	n += varint.Uint16.Marshal(v.Uint16, bs[n:])
	n += raw.Uint8.Marshal(v.Uint8, bs[n:])
	n += raw.Float64.Marshal(v.Float64, bs[n:])
	n += raw.Float32.Marshal(v.Float32, bs[n:])
	n += raw.Uint8.Marshal(v.Byte, bs[n:])
	n += ord.Bool.Marshal(v.Bool, bs[n:])
	n += ord.String.Marshal(v.Str, bs[n:])
	n += ord.ByteSlice.Marshal(v.ByteSlice, bs[n:])
	n += ord.ByteSlice.Marshal(v.Uint8Slice, bs[n:])
	n += raw.TimeUnixUTC.Marshal(v.Time, bs[n:])
	n += ptrTZrSs3BTZxtZSyN70GGz8gΞΞ.Marshal(v.PtrInt, bs[n:])
	n += arraykhqoj8H1iZDaFGbnRRNCSQΞΞ.Marshal(v.ArrayInt, bs[n:])
	n += slicea9b54NTckjaAZ77kX9CsBAΞΞ.Marshal(v.SliceInt, bs[n:])
	n += mapHfQsz6AeCIBt4MICw0pP6QΞΞ.Marshal(v.MapStrInt, bs[n:])
	n += FullDefinedMUS.Marshal(v.Defined, bs[n:])
	n += FullInterfaceMUS.Marshal(v.Interface, bs[n:])
	return n + VersionedMUS.Marshal(v.Versioned, bs[n:])
}

func (s fullStructMUS) Unmarshal(bs []byte) (v mode.FullStruct, n int, err error) {
	v.Int, n, err = varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	v.Int64, n1, err = varint.Int64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int32, n1, err = varint.Int32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int16, n1, err = varint.Int16.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Int8, n1, err = raw.Int8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint, n1, err = varint.Uint.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint64, n1, err = varint.Uint64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint32, n1, err = varint.Uint32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint16, n1, err = varint.Uint16.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint8, n1, err = raw.Uint8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Float64, n1, err = raw.Float64.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Float32, n1, err = raw.Float32.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Byte, n1, err = raw.Uint8.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Bool, n1, err = ord.Bool.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Str, n1, err = ord.String.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.ByteSlice, n1, err = ord.ByteSlice.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Uint8Slice, n1, err = ord.ByteSlice.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Time, n1, err = raw.TimeUnixUTC.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.PtrInt, n1, err = ptrTZrSs3BTZxtZSyN70GGz8gΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.ArrayInt, n1, err = arraykhqoj8H1iZDaFGbnRRNCSQΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.SliceInt, n1, err = slicea9b54NTckjaAZ77kX9CsBAΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.MapStrInt, n1, err = mapHfQsz6AeCIBt4MICw0pP6QΞΞ.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Defined, n1, err = FullDefinedMUS.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Interface, n1, err = FullInterfaceMUS.Unmarshal(bs[n:])
	n += n1
	if err != nil {
		return
	}
	v.Versioned, n1, err = VersionedMUS.Unmarshal(bs[n:])
	n += n1
	return
}

func (s fullStructMUS) Size(v mode.FullStruct) (size int) {
	size = varint.Int.Size(v.Int)
	size += varint.Int64.Size(v.Int64)
	size += varint.Int32.Size(v.Int32)
	size += varint.Int16.Size(v.Int16)
	size += raw.Int8.Size(v.Int8)
	size += varint.Uint.Size(v.Uint)
	size += varint.Uint64.Size(v.Uint64)
	size += varint.Uint32.Size(v.Uint32)
	size += varint.Uint16.Size(v.Uint16)
	size += raw.Uint8.Size(v.Uint8)
	size += raw.Float64.Size(v.Float64)
	size += raw.Float32.Size(v.Float32)
	size += raw.Uint8.Size(v.Byte)
	size += ord.Bool.Size(v.Bool)
	size += ord.String.Size(v.Str)
	size += ord.ByteSlice.Size(v.ByteSlice)
	size += ord.ByteSlice.Size(v.Uint8Slice)
	size += raw.TimeUnixUTC.Size(v.Time)
	size += ptrTZrSs3BTZxtZSyN70GGz8gΞΞ.Size(v.PtrInt)
	size += arraykhqoj8H1iZDaFGbnRRNCSQΞΞ.Size(v.ArrayInt)
	size += slicea9b54NTckjaAZ77kX9CsBAΞΞ.Size(v.SliceInt)
	size += mapHfQsz6AeCIBt4MICw0pP6QΞΞ.Size(v.MapStrInt)
	size += FullDefinedMUS.Size(v.Defined)
	size += FullInterfaceMUS.Size(v.Interface)
	return size + VersionedMUS.Size(v.Versioned)
}

func (s fullStructMUS) Skip(bs []byte) (n int, err error) {
	n, err = varint.Int.Skip(bs)
	if err != nil {
		return
	}
	var n1 int
	n1, err = varint.Int64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Int32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Int16.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Int8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = varint.Uint16.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Uint8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Float64.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Float32.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.Uint8.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.Bool.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.String.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ord.ByteSlice.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = raw.TimeUnixUTC.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = ptrTZrSs3BTZxtZSyN70GGz8gΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = arraykhqoj8H1iZDaFGbnRRNCSQΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = slicea9b54NTckjaAZ77kX9CsBAΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = mapHfQsz6AeCIBt4MICw0pP6QΞΞ.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = FullDefinedMUS.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = FullInterfaceMUS.Skip(bs[n:])
	n += n1
	if err != nil {
		return
	}
	n1, err = VersionedMUS.Skip(bs[n:])
	n += n1
	return
}
