// Code generated by mus-gen-go. DO NOT EDIT.

package pkg2

import "github.com/mus-format/mus-gen-go/test/genopts/multi-package/pkg1"

var BarMUS = barMUS{}

type barMUS struct{}

func (s barMUS) Marshal(v Bar, bs []byte) (n int) {
	return pkg1.FooMUS.Marshal(v.Foo, bs)
}

func (s barMUS) Unmarshal(bs []byte) (v Bar, n int, err error) {
	v.Foo, n, err = pkg1.FooMUS.Unmarshal(bs)
	return
}

func (s barMUS) Size(v Bar) (size int) {
	return pkg1.FooMUS.Size(v.Foo)
}

func (s barMUS) Skip(bs []byte) (n int, err error) {
	n, err = pkg1.FooMUS.Skip(bs)
	return
}
