// Code generated by musgen-go. DO NOT EDIT.

package testutil

import (
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/varint"
)

var (
	ptrLNiHQumtEyMVJXeulΔwΣoAΞΞ = ord.NewPtrSer[int](varint.Int)
)

var MyIntPtrMUS = myIntPtrMUS{}

type myIntPtrMUS struct{}

func (s myIntPtrMUS) Marshal(v MyIntPtr, bs []byte) (n int) {
	return ptrLNiHQumtEyMVJXeulΔwΣoAΞΞ.Marshal((*int)(v), bs)
}

func (s myIntPtrMUS) Unmarshal(bs []byte) (v MyIntPtr, n int, err error) {
	tmp, n, err := ptrLNiHQumtEyMVJXeulΔwΣoAΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = MyIntPtr(tmp)
	return
}

func (s myIntPtrMUS) Size(v MyIntPtr) (size int) {
	return ptrLNiHQumtEyMVJXeulΔwΣoAΞΞ.Size((*int)(v))
}

func (s myIntPtrMUS) Skip(bs []byte) (n int, err error) {
	return ptrLNiHQumtEyMVJXeulΔwΣoAΞΞ.Skip(bs)
}
