// Code generated by musgen-go. DO NOT EDIT.

package testutil

import (
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/varint"
)

var (
	ptrQkMxdmMgkmF3f4DFuSwRΣAΞΞ   = ord.NewPtrSer[MyStruct](MyStructMUS)
	ptrgBvfJBbΣYibM8Y1ivguSrwΞΞ   = ord.NewPtrSer[int](varint.Int)
	ptrΣZ8nUeyhtoPvqkΔtc9EKJgΞΞ   = ord.NewPtrSer[[]int](sliceO4gxVbpViAIFhuOSiDrQFQΞΞ)
	sliceO4gxVbpViAIFhuOSiDrQFQΞΞ = ord.NewSliceSer[int](varint.Int)
)

var MyIntPtrMUS = myIntPtrMUS{}

type myIntPtrMUS struct{}

func (s myIntPtrMUS) Marshal(v MyIntPtr, bs []byte) (n int) {
	return ptrgBvfJBbΣYibM8Y1ivguSrwΞΞ.Marshal((*int)(v), bs)
}

func (s myIntPtrMUS) Unmarshal(bs []byte) (v MyIntPtr, n int, err error) {
	tmp, n, err := ptrgBvfJBbΣYibM8Y1ivguSrwΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = MyIntPtr(tmp)
	return
}

func (s myIntPtrMUS) Size(v MyIntPtr) (size int) {
	return ptrgBvfJBbΣYibM8Y1ivguSrwΞΞ.Size((*int)(v))
}

func (s myIntPtrMUS) Skip(bs []byte) (n int, err error) {
	return ptrgBvfJBbΣYibM8Y1ivguSrwΞΞ.Skip(bs)
}

var MySlicePtrMUS = mySlicePtrMUS{}

type mySlicePtrMUS struct{}

func (s mySlicePtrMUS) Marshal(v MySlicePtr, bs []byte) (n int) {
	return ptrΣZ8nUeyhtoPvqkΔtc9EKJgΞΞ.Marshal((*[]int)(v), bs)
}

func (s mySlicePtrMUS) Unmarshal(bs []byte) (v MySlicePtr, n int, err error) {
	tmp, n, err := ptrΣZ8nUeyhtoPvqkΔtc9EKJgΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = MySlicePtr(tmp)
	return
}

func (s mySlicePtrMUS) Size(v MySlicePtr) (size int) {
	return ptrΣZ8nUeyhtoPvqkΔtc9EKJgΞΞ.Size((*[]int)(v))
}

func (s mySlicePtrMUS) Skip(bs []byte) (n int, err error) {
	return ptrΣZ8nUeyhtoPvqkΔtc9EKJgΞΞ.Skip(bs)
}

var MyStructMUS = myStructMUS{}

type myStructMUS struct{}

func (s myStructMUS) Marshal(v MyStruct, bs []byte) (n int) {
	return
}

func (s myStructMUS) Unmarshal(bs []byte) (v MyStruct, n int, err error) {
	return
}

func (s myStructMUS) Size(v MyStruct) (size int) {
	return
}

func (s myStructMUS) Skip(bs []byte) (n int, err error) {
	return
}

var MyStructPtrMUS = myStructPtrMUS{}

type myStructPtrMUS struct{}

func (s myStructPtrMUS) Marshal(v MyStructPtr, bs []byte) (n int) {
	return ptrQkMxdmMgkmF3f4DFuSwRΣAΞΞ.Marshal((*MyStruct)(v), bs)
}

func (s myStructPtrMUS) Unmarshal(bs []byte) (v MyStructPtr, n int, err error) {
	tmp, n, err := ptrQkMxdmMgkmF3f4DFuSwRΣAΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = MyStructPtr(tmp)
	return
}

func (s myStructPtrMUS) Size(v MyStructPtr) (size int) {
	return ptrQkMxdmMgkmF3f4DFuSwRΣAΞΞ.Size((*MyStruct)(v))
}

func (s myStructPtrMUS) Skip(bs []byte) (n int, err error) {
	return ptrQkMxdmMgkmF3f4DFuSwRΣAΞΞ.Skip(bs)
}
