// Code generated by mus-gen. DO NOT EDIT.

package types

import (
	com "github.com/mus-format/common-go"
	arropts "github.com/mus-format/mus-go/options/array"
	mapopts "github.com/mus-format/mus-go/options/map"
	slopts "github.com/mus-format/mus-go/options/slice"
	stropts "github.com/mus-format/mus-go/options/string"
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/raw"
	"github.com/mus-format/mus-go/unsafe"
	"github.com/mus-format/mus-go/varint"
)

var (
	array5OgmvUg3UeD4dq6anVO3QAΞΞ  = unsafe.NewArraySer[[3]int](varint.Int, arropts.WithLenSer[int](raw.Int))
	arrayk1TPΣVicOyoeZCerey6UjQΞΞ  = unsafe.NewValidArraySer[[3]int](varint.Int, arropts.WithElemValidator[int](com.ValidatorFn[int](ValidateNum)))
	arraykhqoj8H1iZDaFGbnRRNCSQΞΞ  = unsafe.NewArraySer[[3]int](varint.Int)
	map3H19Zv6tpd93ZnWuxgbA2wΞΞ    = ord.NewMapSer[string, Struct](ord.String, StructMUS)
	map89KZyΔeUWMY73bC2RIToOAΞΞ    = ord.NewMapSer[*[]int, [][]float32](ptrGzR0RzrΣC1z2yTa8UMKDhwΞΞ, slicegZDr1Nz2sdCWxS01Iu9ΣqAΞΞ)
	mapDSkPadp5azAvSTicXTzBQAΞΞ    = ord.NewMapSer[string, int](ord.String, varint.Int, mapopts.WithLenSer[string, int](raw.Int))
	mapHfQsz6AeCIBt4MICw0pP6QΞΞ    = ord.NewMapSer[string, int](ord.String, varint.Int)
	mapq2eFIqbCNvksgCaR1ΔhΔpwΞΞ    = ord.NewValidMapSer[string, int](ord.String, varint.Int, mapopts.WithLenValidator[string, int](com.ValidatorFn[int](ValidateLen)), mapopts.WithKeyValidator[string, int](com.ValidatorFn[string](ValidateStr)), mapopts.WithValueValidator[string, int](com.ValidatorFn[int](ValidateNum)))
	mapvJWRrmd358YxΔFbTfawohAΞΞ    = ord.NewValidMapSer[string, map[*[]int][][]float32](ord.String, map89KZyΔeUWMY73bC2RIToOAΞΞ, mapopts.WithLenValidator[string, map[*[]int][][]float32](com.ValidatorFn[int](ValidateLen)), mapopts.WithValueValidator[string, map[*[]int][][]float32](com.ValidatorFn[map[*[]int][][]float32](ValidateComplexMapValue)))
	ptrGzR0RzrΣC1z2yTa8UMKDhwΞΞ    = ord.NewPtrSer[[]int](slicea9b54NTckjaAZ77kX9CsBAΞΞ)
	ptrP2qMjfiDo6EtΣxlQsΣELIgΞΞ    = ord.NewPtrSer[Struct](StructMUS)
	ptrceΔUj8v42zbVCknwTKfRXwΞΞ    = ord.NewPtrSer[int](varint.Int)
	slice3ΔOkaLLzjΔyjeGΔI5kD0QwΞΞ  = ord.NewSliceSer[float32](raw.Float32)
	slicea9b54NTckjaAZ77kX9CsBAΞΞ  = ord.NewSliceSer[int](varint.Int)
	sliceadSpy8O6qUrsL27kWjDtvgΞΞ  = ord.NewSliceSer[int](varint.Int, slopts.WithLenSer[int](raw.Int))
	slicegZDr1Nz2sdCWxS01Iu9ΣqAΞΞ  = ord.NewSliceSer[[]float32](slice3ΔOkaLLzjΔyjeGΔI5kD0QwΞΞ)
	slicenCeoXNSYzlok379Yg0oL1gΞΞ  = ord.NewValidSliceSer[int](varint.Int, slopts.WithLenValidator[int](com.ValidatorFn[int](ValidateLen)), slopts.WithElemValidator[int](com.ValidatorFn[int](ValidateNum)))
	slicewhtdz4o0ieFFORszI7KVjQΞΞ  = ord.NewSliceSer[Struct](StructMUS)
	stringCf1Ey8FtcNLgmRwz5SpmsAΞΞ = ord.NewValidStringSer(stropts.WithLenValidator(com.ValidatorFn[int](ValidateLen)))
	stringqFVnrHp7ZΣjJ2aVgZZfKSwΞΞ = ord.NewStringSer(stropts.WithLenSer(raw.Int))
)

var LenStringMUS = lenStringMUS{}

type lenStringMUS struct{}

func (s lenStringMUS) Marshal(v LenString, bs []byte) (n int) {
	return stringqFVnrHp7ZΣjJ2aVgZZfKSwΞΞ.Marshal(string(v), bs)
}

func (s lenStringMUS) Unmarshal(bs []byte) (v LenString, n int, err error) {
	tmp, n, err := stringqFVnrHp7ZΣjJ2aVgZZfKSwΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = LenString(tmp)
	return
}

func (s lenStringMUS) Size(v LenString) (size int) {
	return stringqFVnrHp7ZΣjJ2aVgZZfKSwΞΞ.Size(string(v))
}

func (s lenStringMUS) Skip(bs []byte) (n int, err error) {
	return stringqFVnrHp7ZΣjJ2aVgZZfKSwΞΞ.Skip(bs)
}

var LenSliceMUS = lenSliceMUS{}

type lenSliceMUS struct{}

func (s lenSliceMUS) Marshal(v LenSlice, bs []byte) (n int) {
	return sliceadSpy8O6qUrsL27kWjDtvgΞΞ.Marshal([]int(v), bs)
}

func (s lenSliceMUS) Unmarshal(bs []byte) (v LenSlice, n int, err error) {
	tmp, n, err := sliceadSpy8O6qUrsL27kWjDtvgΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = LenSlice(tmp)
	return
}

func (s lenSliceMUS) Size(v LenSlice) (size int) {
	return sliceadSpy8O6qUrsL27kWjDtvgΞΞ.Size([]int(v))
}

func (s lenSliceMUS) Skip(bs []byte) (n int, err error) {
	return sliceadSpy8O6qUrsL27kWjDtvgΞΞ.Skip(bs)
}

var LenArrayMUS = lenArrayMUS{}

type lenArrayMUS struct{}

func (s lenArrayMUS) Marshal(v LenArray, bs []byte) (n int) {
	return array5OgmvUg3UeD4dq6anVO3QAΞΞ.Marshal([3]int(v), bs)
}

func (s lenArrayMUS) Unmarshal(bs []byte) (v LenArray, n int, err error) {
	tmp, n, err := array5OgmvUg3UeD4dq6anVO3QAΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = LenArray(tmp)
	return
}

func (s lenArrayMUS) Size(v LenArray) (size int) {
	return array5OgmvUg3UeD4dq6anVO3QAΞΞ.Size([3]int(v))
}

func (s lenArrayMUS) Skip(bs []byte) (n int, err error) {
	return array5OgmvUg3UeD4dq6anVO3QAΞΞ.Skip(bs)
}

var LenMapMUS = lenMapMUS{}

type lenMapMUS struct{}

func (s lenMapMUS) Marshal(v LenMap, bs []byte) (n int) {
	return mapDSkPadp5azAvSTicXTzBQAΞΞ.Marshal(map[string]int(v), bs)
}

func (s lenMapMUS) Unmarshal(bs []byte) (v LenMap, n int, err error) {
	tmp, n, err := mapDSkPadp5azAvSTicXTzBQAΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = LenMap(tmp)
	return
}

func (s lenMapMUS) Size(v LenMap) (size int) {
	return mapDSkPadp5azAvSTicXTzBQAΞΞ.Size(map[string]int(v))
}

func (s lenMapMUS) Skip(bs []byte) (n int, err error) {
	return mapDSkPadp5azAvSTicXTzBQAΞΞ.Skip(bs)
}

var SliceMUS = sliceMUS{}

type sliceMUS struct{}

func (s sliceMUS) Marshal(v Slice, bs []byte) (n int) {
	return slicea9b54NTckjaAZ77kX9CsBAΞΞ.Marshal([]int(v), bs)
}

func (s sliceMUS) Unmarshal(bs []byte) (v Slice, n int, err error) {
	tmp, n, err := slicea9b54NTckjaAZ77kX9CsBAΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Slice(tmp)
	return
}

func (s sliceMUS) Size(v Slice) (size int) {
	return slicea9b54NTckjaAZ77kX9CsBAΞΞ.Size([]int(v))
}

func (s sliceMUS) Skip(bs []byte) (n int, err error) {
	return slicea9b54NTckjaAZ77kX9CsBAΞΞ.Skip(bs)
}

var ArrayMUS = arrayMUS{}

type arrayMUS struct{}

func (s arrayMUS) Marshal(v Array, bs []byte) (n int) {
	return arraykhqoj8H1iZDaFGbnRRNCSQΞΞ.Marshal([3]int(v), bs)
}

func (s arrayMUS) Unmarshal(bs []byte) (v Array, n int, err error) {
	tmp, n, err := arraykhqoj8H1iZDaFGbnRRNCSQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Array(tmp)
	return
}

func (s arrayMUS) Size(v Array) (size int) {
	return arraykhqoj8H1iZDaFGbnRRNCSQΞΞ.Size([3]int(v))
}

func (s arrayMUS) Skip(bs []byte) (n int, err error) {
	return arraykhqoj8H1iZDaFGbnRRNCSQΞΞ.Skip(bs)
}

var MapMUS = mapMUS{}

type mapMUS struct{}

func (s mapMUS) Marshal(v Map, bs []byte) (n int) {
	return mapHfQsz6AeCIBt4MICw0pP6QΞΞ.Marshal(map[string]int(v), bs)
}

func (s mapMUS) Unmarshal(bs []byte) (v Map, n int, err error) {
	tmp, n, err := mapHfQsz6AeCIBt4MICw0pP6QΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Map(tmp)
	return
}

func (s mapMUS) Size(v Map) (size int) {
	return mapHfQsz6AeCIBt4MICw0pP6QΞΞ.Size(map[string]int(v))
}

func (s mapMUS) Skip(bs []byte) (n int, err error) {
	return mapHfQsz6AeCIBt4MICw0pP6QΞΞ.Skip(bs)
}

var PtrMUS = ptrMUS{}

type ptrMUS struct{}

func (s ptrMUS) Marshal(v Ptr, bs []byte) (n int) {
	return ptrceΔUj8v42zbVCknwTKfRXwΞΞ.Marshal((*int)(v), bs)
}

func (s ptrMUS) Unmarshal(bs []byte) (v Ptr, n int, err error) {
	tmp, n, err := ptrceΔUj8v42zbVCknwTKfRXwΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Ptr(tmp)
	return
}

func (s ptrMUS) Size(v Ptr) (size int) {
	return ptrceΔUj8v42zbVCknwTKfRXwΞΞ.Size((*int)(v))
}

func (s ptrMUS) Skip(bs []byte) (n int, err error) {
	return ptrceΔUj8v42zbVCknwTKfRXwΞΞ.Skip(bs)
}

var ValidStringMUS = validStringMUS{}

type validStringMUS struct{}

func (s validStringMUS) Marshal(v ValidString, bs []byte) (n int) {
	return stringCf1Ey8FtcNLgmRwz5SpmsAΞΞ.Marshal(string(v), bs)
}

func (s validStringMUS) Unmarshal(bs []byte) (v ValidString, n int, err error) {
	tmp, n, err := stringCf1Ey8FtcNLgmRwz5SpmsAΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ValidString(tmp)
	return
}

func (s validStringMUS) Size(v ValidString) (size int) {
	return stringCf1Ey8FtcNLgmRwz5SpmsAΞΞ.Size(string(v))
}

func (s validStringMUS) Skip(bs []byte) (n int, err error) {
	return stringCf1Ey8FtcNLgmRwz5SpmsAΞΞ.Skip(bs)
}

var ValidSliceMUS = validSliceMUS{}

type validSliceMUS struct{}

func (s validSliceMUS) Marshal(v ValidSlice, bs []byte) (n int) {
	return slicenCeoXNSYzlok379Yg0oL1gΞΞ.Marshal([]int(v), bs)
}

func (s validSliceMUS) Unmarshal(bs []byte) (v ValidSlice, n int, err error) {
	tmp, n, err := slicenCeoXNSYzlok379Yg0oL1gΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ValidSlice(tmp)
	return
}

func (s validSliceMUS) Size(v ValidSlice) (size int) {
	return slicenCeoXNSYzlok379Yg0oL1gΞΞ.Size([]int(v))
}

func (s validSliceMUS) Skip(bs []byte) (n int, err error) {
	return slicenCeoXNSYzlok379Yg0oL1gΞΞ.Skip(bs)
}

var ValidArrayMUS = validArrayMUS{}

type validArrayMUS struct{}

func (s validArrayMUS) Marshal(v ValidArray, bs []byte) (n int) {
	return arrayk1TPΣVicOyoeZCerey6UjQΞΞ.Marshal([3]int(v), bs)
}

func (s validArrayMUS) Unmarshal(bs []byte) (v ValidArray, n int, err error) {
	tmp, n, err := arrayk1TPΣVicOyoeZCerey6UjQΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ValidArray(tmp)
	return
}

func (s validArrayMUS) Size(v ValidArray) (size int) {
	return arrayk1TPΣVicOyoeZCerey6UjQΞΞ.Size([3]int(v))
}

func (s validArrayMUS) Skip(bs []byte) (n int, err error) {
	return arrayk1TPΣVicOyoeZCerey6UjQΞΞ.Skip(bs)
}

var ValidMapMUS = validMapMUS{}

type validMapMUS struct{}

func (s validMapMUS) Marshal(v ValidMap, bs []byte) (n int) {
	return mapq2eFIqbCNvksgCaR1ΔhΔpwΞΞ.Marshal(map[string]int(v), bs)
}

func (s validMapMUS) Unmarshal(bs []byte) (v ValidMap, n int, err error) {
	tmp, n, err := mapq2eFIqbCNvksgCaR1ΔhΔpwΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ValidMap(tmp)
	return
}

func (s validMapMUS) Size(v ValidMap) (size int) {
	return mapq2eFIqbCNvksgCaR1ΔhΔpwΞΞ.Size(map[string]int(v))
}

func (s validMapMUS) Skip(bs []byte) (n int, err error) {
	return mapq2eFIqbCNvksgCaR1ΔhΔpwΞΞ.Skip(bs)
}

var ComplexMapMUS = complexMapMUS{}

type complexMapMUS struct{}

func (s complexMapMUS) Marshal(v ComplexMap, bs []byte) (n int) {
	return mapvJWRrmd358YxΔFbTfawohAΞΞ.Marshal(map[string]map[*[]int][][]float32(v), bs)
}

func (s complexMapMUS) Unmarshal(bs []byte) (v ComplexMap, n int, err error) {
	tmp, n, err := mapvJWRrmd358YxΔFbTfawohAΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	v = ComplexMap(tmp)
	return
}

func (s complexMapMUS) Size(v ComplexMap) (size int) {
	return mapvJWRrmd358YxΔFbTfawohAΞΞ.Size(map[string]map[*[]int][][]float32(v))
}

func (s complexMapMUS) Skip(bs []byte) (n int, err error) {
	return mapvJWRrmd358YxΔFbTfawohAΞΞ.Skip(bs)
}

var StructMUS = structMUS{}

type structMUS struct{}

func (s structMUS) Marshal(v Struct, bs []byte) (n int) {
	return
}

func (s structMUS) Unmarshal(bs []byte) (v Struct, n int, err error) {
	return
}

func (s structMUS) Size(v Struct) (size int) {
	return
}

func (s structMUS) Skip(bs []byte) (n int, err error) {
	return
}

var PtrStructMUS = ptrStructMUS{}

type ptrStructMUS struct{}

func (s ptrStructMUS) Marshal(v PtrStruct, bs []byte) (n int) {
	return ptrP2qMjfiDo6EtΣxlQsΣELIgΞΞ.Marshal(v.Ptr, bs)
}

func (s ptrStructMUS) Unmarshal(bs []byte) (v PtrStruct, n int, err error) {
	v.Ptr, n, err = ptrP2qMjfiDo6EtΣxlQsΣELIgΞΞ.Unmarshal(bs)
	return
}

func (s ptrStructMUS) Size(v PtrStruct) (size int) {
	return ptrP2qMjfiDo6EtΣxlQsΣELIgΞΞ.Size(v.Ptr)
}

func (s ptrStructMUS) Skip(bs []byte) (n int, err error) {
	n, err = ptrP2qMjfiDo6EtΣxlQsΣELIgΞΞ.Skip(bs)
	return
}

var MapStructMUS = mapStructMUS{}

type mapStructMUS struct{}

func (s mapStructMUS) Marshal(v MapStruct, bs []byte) (n int) {
	return map3H19Zv6tpd93ZnWuxgbA2wΞΞ.Marshal(v.Map, bs)
}

func (s mapStructMUS) Unmarshal(bs []byte) (v MapStruct, n int, err error) {
	v.Map, n, err = map3H19Zv6tpd93ZnWuxgbA2wΞΞ.Unmarshal(bs)
	return
}

func (s mapStructMUS) Size(v MapStruct) (size int) {
	return map3H19Zv6tpd93ZnWuxgbA2wΞΞ.Size(v.Map)
}

func (s mapStructMUS) Skip(bs []byte) (n int, err error) {
	n, err = map3H19Zv6tpd93ZnWuxgbA2wΞΞ.Skip(bs)
	return
}

var SliceStructMUS = sliceStructMUS{}

type sliceStructMUS struct{}

func (s sliceStructMUS) Marshal(v SliceStruct, bs []byte) (n int) {
	return slicewhtdz4o0ieFFORszI7KVjQΞΞ.Marshal(v.Slice, bs)
}

func (s sliceStructMUS) Unmarshal(bs []byte) (v SliceStruct, n int, err error) {
	v.Slice, n, err = slicewhtdz4o0ieFFORszI7KVjQΞΞ.Unmarshal(bs)
	return
}

func (s sliceStructMUS) Size(v SliceStruct) (size int) {
	return slicewhtdz4o0ieFFORszI7KVjQΞΞ.Size(v.Slice)
}

func (s sliceStructMUS) Skip(bs []byte) (n int, err error) {
	n, err = slicewhtdz4o0ieFFORszI7KVjQΞΞ.Skip(bs)
	return
}
