// Code generated by mus-gen-go. DO NOT EDIT.

package types

import (
	"fmt"

	com "github.com/mus-format/common-go"
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/typed"
	"github.com/mus-format/mus-go/varint"
)

const (
	Impl3DTM com.DTM = iota + 1
	Impl4DTM
)

const (
	Impl5DTM com.DTM = iota + 1
	Impl6DTM
)

var Impl3MUS = impl3MUS{}

type impl3MUS struct{}

func (s impl3MUS) Marshal(v Impl3, bs []byte) (n int) {
	return varint.Int.Marshal(v.Num, bs)
}

func (s impl3MUS) Unmarshal(bs []byte) (v Impl3, n int, err error) {
	v.Num, n, err = varint.Int.Unmarshal(bs)
	return
}

func (s impl3MUS) Size(v Impl3) (size int) {
	return varint.Int.Size(v.Num)
}

func (s impl3MUS) Skip(bs []byte) (n int, err error) {
	n, err = varint.Int.Skip(bs)
	return
}

var Impl3TypedMUS = typed.NewTypedSer(Impl3DTM, Impl3MUS)

var Impl4MUS = impl4MUS{}

type impl4MUS struct{}

func (s impl4MUS) Marshal(v Impl4, bs []byte) (n int) {
	return ord.String.Marshal(string(v), bs)
}

func (s impl4MUS) Unmarshal(bs []byte) (v Impl4, n int, err error) {
	tmp, n, err := ord.String.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Impl4(tmp)
	return
}

func (s impl4MUS) Size(v Impl4) (size int) {
	return ord.String.Size(string(v))
}

func (s impl4MUS) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}

var Impl4TypedMUS = typed.NewTypedSer(Impl4DTM, Impl4MUS)

var InterfaceRegisterMUS = interfaceRegisterMUS{}

type interfaceRegisterMUS struct{}

func (s interfaceRegisterMUS) Marshal(v InterfaceRegister, bs []byte) (n int) {
	switch t := v.(type) {
	case Impl3:
		return Impl3TypedMUS.Marshal(t, bs)
	case Impl4:
		return Impl4TypedMUS.Marshal(t, bs)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s interfaceRegisterMUS) Unmarshal(bs []byte) (v InterfaceRegister, n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case Impl3DTM:
		v, n1, err = Impl3TypedMUS.UnmarshalData(bs[n:])
	case Impl4DTM:
		v, n1, err = Impl4TypedMUS.UnmarshalData(bs[n:])
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

func (s interfaceRegisterMUS) Size(v InterfaceRegister) (size int) {
	switch t := v.(type) {
	case Impl3:
		return Impl3TypedMUS.Size(t)
	case Impl4:
		return Impl4TypedMUS.Size(t)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s interfaceRegisterMUS) Skip(bs []byte) (n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case Impl3DTM:
		n1, err = Impl3TypedMUS.SkipData(bs[n:])
	case Impl4DTM:
		n1, err = Impl4TypedMUS.SkipData(bs[n:])
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

var Impl5MUS = impl5MUS{}

type impl5MUS struct{}

func (s impl5MUS) Marshal(v Impl5, bs []byte) (n int) {
	return varint.Int.Marshal(v.Num, bs)
}

func (s impl5MUS) Unmarshal(bs []byte) (v Impl5, n int, err error) {
	v.Num, n, err = varint.Int.Unmarshal(bs)
	return
}

func (s impl5MUS) Size(v Impl5) (size int) {
	return varint.Int.Size(v.Num)
}

func (s impl5MUS) Skip(bs []byte) (n int, err error) {
	n, err = varint.Int.Skip(bs)
	return
}

var Impl5TypedMUS = typed.NewTypedSer(Impl5DTM, Impl5MUS)

var Impl6MUS = impl6MUS{}

type impl6MUS struct{}

func (s impl6MUS) Marshal(v Impl6, bs []byte) (n int) {
	return ord.String.Marshal(string(v), bs)
}

func (s impl6MUS) Unmarshal(bs []byte) (v Impl6, n int, err error) {
	tmp, n, err := ord.String.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Impl6(tmp)
	return
}

func (s impl6MUS) Size(v Impl6) (size int) {
	return ord.String.Size(string(v))
}

func (s impl6MUS) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}

var Impl6TypedMUS = typed.NewTypedSer(Impl6DTM, Impl6MUS)

var MarshallerInterfaceRegisterMUS = marshallerInterfaceRegisterMUS{}

type marshallerInterfaceRegisterMUS struct{}

func (s marshallerInterfaceRegisterMUS) Marshal(v MarshallerInterfaceRegister, bs []byte) (n int) {
	switch t := v.(type) {
	case Impl5:
		return Impl5TypedMUS.Marshal(t, bs)
	case Impl6:
		return Impl6TypedMUS.Marshal(t, bs)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s marshallerInterfaceRegisterMUS) Unmarshal(bs []byte) (v MarshallerInterfaceRegister, n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case Impl5DTM:
		v, n1, err = Impl5TypedMUS.UnmarshalData(bs[n:])
	case Impl6DTM:
		v, n1, err = Impl6TypedMUS.UnmarshalData(bs[n:])
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

func (s marshallerInterfaceRegisterMUS) Size(v MarshallerInterfaceRegister) (size int) {
	switch t := v.(type) {
	case Impl5:
		return Impl5TypedMUS.Size(t)
	case Impl6:
		return Impl6TypedMUS.Size(t)
	default:
		panic(fmt.Sprintf(com.ErrorPrefix+"unexpected %v type", t))
	}
}

func (s marshallerInterfaceRegisterMUS) Skip(bs []byte) (n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case Impl5DTM:
		n1, err = Impl5TypedMUS.SkipData(bs[n:])
	case Impl6DTM:
		n1, err = Impl6TypedMUS.SkipData(bs[n:])
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}
