// Code generated by mus-gen. DO NOT EDIT.

package types

import (
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/varint"
)

var (
	ptrYHh3rdfcksWaWFk7eHXSXgΞΞ = ord.NewPtrSer(varint.Int16)
	ptrcAmNSUk4Σ2KbOysZ5YKZHgΞΞ = ord.NewPtrSer(varint.Uint16)
)

var MultiPtrStructMUS = multiPtrStructMUS{}

type multiPtrStructMUS struct{}

func (s multiPtrStructMUS) Marshal(v MultiPtrStruct, bs []byte) (n int) {
	n = ptrYHh3rdfcksWaWFk7eHXSXgΞΞ.Marshal(v.Num1, bs)
	return n + ptrcAmNSUk4Σ2KbOysZ5YKZHgΞΞ.Marshal(v.Num2, bs[n:])
}

func (s multiPtrStructMUS) Unmarshal(bs []byte) (v MultiPtrStruct, n int, err error) {
	v.Num1, n, err = ptrYHh3rdfcksWaWFk7eHXSXgΞΞ.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	v.Num2, n1, err = ptrcAmNSUk4Σ2KbOysZ5YKZHgΞΞ.Unmarshal(bs[n:])
	n += n1
	return
}

func (s multiPtrStructMUS) Size(v MultiPtrStruct) (size int) {
	size = ptrYHh3rdfcksWaWFk7eHXSXgΞΞ.Size(v.Num1)
	return size + ptrcAmNSUk4Σ2KbOysZ5YKZHgΞΞ.Size(v.Num2)
}

func (s multiPtrStructMUS) Skip(bs []byte) (n int, err error) {
	n, err = ptrYHh3rdfcksWaWFk7eHXSXgΞΞ.Skip(bs)
	if err != nil {
		return
	}
	var n1 int
	n1, err = ptrcAmNSUk4Σ2KbOysZ5YKZHgΞΞ.Skip(bs[n:])
	n += n1
	return
}
