// Code generated by mus-gen. DO NOT EDIT.

package types

import (
	com "github.com/mus-format/common-go"
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/typed"
	"github.com/mus-format/mus-go/varint"
)

var Ver1MUS = ver1MUS{}

type ver1MUS struct{}

func (s ver1MUS) Marshal(v Ver1, bs []byte) (n int) {
	return varint.Int.Marshal(int(v), bs)
}

func (s ver1MUS) Unmarshal(bs []byte) (v Ver1, n int, err error) {
	tmp, n, err := varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Ver1(tmp)
	return
}

func (s ver1MUS) Size(v Ver1) (size int) {
	return varint.Int.Size(int(v))
}

func (s ver1MUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

var Ver2MUS = ver2MUS{}

type ver2MUS struct{}

func (s ver2MUS) Marshal(v Ver2, bs []byte) (n int) {
	return ord.String.Marshal(string(v), bs)
}

func (s ver2MUS) Unmarshal(bs []byte) (v Ver2, n int, err error) {
	tmp, n, err := ord.String.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Ver2(tmp)
	return
}

func (s ver2MUS) Size(v Ver2) (size int) {
	return ord.String.Size(string(v))
}

func (s ver2MUS) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}

var Ver1TypedMUS = typed.NewSer(Ver1DTM, Ver1MUS)

var Ver2TypedMUS = typed.NewSer(Ver2DTM, Ver2MUS)

var VersionedMUS = versionedMUS{}

type versionedMUS struct{}

func (s versionedMUS) Marshal(v Versioned, bs []byte) (n int) {
	return Ver2TypedMUS.Marshal(Ver2(v), bs)
}

func (s versionedMUS) Unmarshal(bs []byte) (v Versioned, n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case Ver1DTM:
		var tmp Ver1
		tmp, n1, err = Ver1TypedMUS.UnmarshalData(bs[n:])
		if err != nil {
			return
		}
		v = MigrateVer1(tmp)
	case Ver2DTM:
		var tmp Ver2
		tmp, n1, err = Ver2TypedMUS.UnmarshalData(bs[n:])
		if err != nil {
			return
		}
		v = Versioned(tmp)
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

func (s versionedMUS) Size(v Versioned) (size int) {
	return Ver2TypedMUS.Size(Ver2(v))
}

func (s versionedMUS) Skip(bs []byte) (n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case Ver1DTM:
		n1, err = Ver1TypedMUS.SkipData(bs[n:])
	case Ver2DTM:
		n1, err = Ver2TypedMUS.SkipData(bs[n:])
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}
