// Code generated by mus-gen. DO NOT EDIT.

package types

import (
	com "github.com/mus-format/common-go"
	"github.com/mus-format/mus-go/ord"
	"github.com/mus-format/mus-go/typed"
	"github.com/mus-format/mus-go/varint"
)

const (
	Ver3DTM com.DTM = iota + 1
	Ver4DTM
)

var Ver3MUS = ver3MUS{}

type ver3MUS struct{}

func (s ver3MUS) Marshal(v Ver3, bs []byte) (n int) {
	return varint.Int.Marshal(int(v), bs)
}

func (s ver3MUS) Unmarshal(bs []byte) (v Ver3, n int, err error) {
	tmp, n, err := varint.Int.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Ver3(tmp)
	return
}

func (s ver3MUS) Size(v Ver3) (size int) {
	return varint.Int.Size(int(v))
}

func (s ver3MUS) Skip(bs []byte) (n int, err error) {
	return varint.Int.Skip(bs)
}

var Ver3TypedMUS = typed.NewSer(Ver3DTM, Ver3MUS)

var Ver4MUS = ver4MUS{}

type ver4MUS struct{}

func (s ver4MUS) Marshal(v Ver4, bs []byte) (n int) {
	return ord.String.Marshal(string(v), bs)
}

func (s ver4MUS) Unmarshal(bs []byte) (v Ver4, n int, err error) {
	tmp, n, err := ord.String.Unmarshal(bs)
	if err != nil {
		return
	}
	v = Ver4(tmp)
	return
}

func (s ver4MUS) Size(v Ver4) (size int) {
	return ord.String.Size(string(v))
}

func (s ver4MUS) Skip(bs []byte) (n int, err error) {
	return ord.String.Skip(bs)
}

var Ver4TypedMUS = typed.NewSer(Ver4DTM, Ver4MUS)

var VersionedRegisterMUS = versionedRegisterMUS{}

type versionedRegisterMUS struct{}

func (s versionedRegisterMUS) Marshal(v VersionedRegister, bs []byte) (n int) {
	return Ver4TypedMUS.Marshal(Ver4(v), bs)
}

func (s versionedRegisterMUS) Unmarshal(bs []byte) (v VersionedRegister, n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case Ver3DTM:
		var tmp Ver3
		tmp, n1, err = Ver3TypedMUS.UnmarshalData(bs[n:])
		if err != nil {
			return
		}
		v = MigrateVer3(tmp)
	case Ver4DTM:
		var tmp Ver4
		tmp, n1, err = Ver4TypedMUS.UnmarshalData(bs[n:])
		if err != nil {
			return
		}
		v = VersionedRegister(tmp)
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}

func (s versionedRegisterMUS) Size(v VersionedRegister) (size int) {
	return Ver4TypedMUS.Size(Ver4(v))
}

func (s versionedRegisterMUS) Skip(bs []byte) (n int, err error) {
	dtm, n, err := typed.DTMSer.Unmarshal(bs)
	if err != nil {
		return
	}
	var n1 int
	switch dtm {
	case Ver3DTM:
		n1, err = Ver3TypedMUS.SkipData(bs[n:])
	case Ver4DTM:
		n1, err = Ver4TypedMUS.SkipData(bs[n:])
	default:
		err = com.NewUnexpectedDTMError(dtm)
		return
	}
	n += n1
	return
}
